"""empty message

Revision ID: 0335ddb6c039
Revises: d41e2c376b02
Create Date: 2020-06-08 14:56:34.117901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0335ddb6c039'
down_revision = 'd41e2c376b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synchronization_filter', sa.Column('filter_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('synchronization_filter', 'filter_type')
    # ### end Alembic commands ###
