"""empty message

Revision ID: 05972cb08ae6
Revises: eb57e7df329a
Create Date: 2018-10-17 15:07:02.202116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05972cb08ae6'
down_revision = 'eb57e7df329a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_whitelist', sa.Column('allow_partial_match', sa.Boolean(), nullable=True))
    op.add_column('email_whitelist', sa.Column('used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_whitelist', 'used')
    op.drop_column('email_whitelist', 'allow_partial_match')
    # ### end Alembic commands ###
