"""empty message

Revision ID: 091221bd6d58
Revises: 0d6d3ce1654d
Create Date: 2019-05-01 15:22:11.520174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091221bd6d58'
down_revision = '0d6d3ce1654d'
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
