"""
Adds batch uuid to credit transfer table
Revision ID: 09edd72433d4
Revises: 49e8a333d285
Create Date: 2020-07-04 10:12:49.015322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09edd72433d4'
down_revision = '49e8a333d285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('batch_uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_transfer', 'batch_uuid')
    # ### end Alembic commands ###
