"""empty message

Revision ID: 0fb2f2fc39d8
Revises: eb55e0465a4a
Create Date: 2019-09-09 05:39:45.417453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb2f2fc39d8'
down_revision = 'eb55e0465a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_application', sa.Column('dob', sa.String(), nullable=True))
    op.drop_column('user', 'ap_paypal_id')
    op.drop_column('user', 'ap_user_id')
    op.drop_column('user', 'kyc_state')
    op.drop_column('user', 'ap_bank_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ap_bank_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('kyc_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('ap_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('ap_paypal_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('kyc_application', 'dob')
    # ### end Alembic commands ###
