"""empty message

Revision ID: 103e570ddb24
Revises: 49e8a333d285
Create Date: 2020-07-03 14:57:35.942456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103e570ddb24'
down_revision = '49e8a333d285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_org_level_account', 'organisation', 'transfer_account', ['org_level_transfer_account_id'], ['id'])
    op.add_column('transfer_account', sa.Column('_balance_offset', sa.Numeric(precision=27), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_account', '_balance_offset')
    op.drop_constraint('fk_org_level_account', 'organisation', type_='foreignkey')
    # ### end Alembic commands ###
