"""Add transfer_type

Revision ID: 12c38a95145f
Revises: 9a8014403afd
Create Date: 2021-03-04 18:22:42.865493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c38a95145f'
down_revision = '9a8014403afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disbursement', sa.Column('transfer_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disbursement', 'transfer_type')
    # ### end Alembic commands ###
