"""empty message

Revision ID: 12c8ae8754c4
Revises: d6a4ab149ae1
Create Date: 2019-07-09 13:46:19.854584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c8ae8754c4'
down_revision = 'd6a4ab149ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_usage', sa.Column('_icon', sa.String(), nullable=True))
    op.drop_column('transfer_usage', 'icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_usage', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transfer_usage', '_icon')
    # ### end Alembic commands ###
