"""Transaction Callback Migration Alteration

Revision ID: 13040d945d12
Revises: d7b89a614ae9
Create Date: 2020-06-12 16:31:52.099008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13040d945d12'
down_revision = 'd7b89a614ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_worker_messages_table_blockchain_task_uuid', table_name='worker_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_worker_messages_table_blockchain_task_uuid', 'worker_messages', ['blockchain_task_uuid'], unique=False)
    # ### end Alembic commands ###
