"""empty message

Revision ID: 131baa8bfa9e
Revises: f5383ac03cf1
Create Date: 2019-05-15 09:37:38.205023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131baa8bfa9e'
down_revision = 'f5383ac03cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorising_user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_attribute')
    # ### end Alembic commands ###
