"""empty message

Revision ID: 132ea53022f1
Revises: 5c5b65647bed
Create Date: 2019-09-23 20:50:48.973712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '132ea53022f1'
down_revision = '5c5b65647bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transfer_card_transfer_account_id_fkey', 'transfer_card', type_='foreignkey')
    op.create_foreign_key(None, 'transfer_card', 'transfer_account', ['transfer_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer_card', type_='foreignkey')
    op.create_foreign_key('transfer_card_transfer_account_id_fkey', 'transfer_card', 'user', ['transfer_account_id'], ['id'])
    # ### end Alembic commands ###
