"""empty message

Revision ID: 1674ba61ae00
Revises: ae519ccf19f0
Create Date: 2019-04-02 19:10:24.870884

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '1674ba61ae00'
down_revision = 'ae519ccf19f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('business_verification', 'kyc_application')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('kyc_application', 'business_verification')
    # ### end Alembic commands ###
