"""empty message

Revision ID: 17269ee60c54
Revises: 38f486afd1ae
Create Date: 2020-10-06 14:02:22.799517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17269ee60c54'
down_revision = '38f486afd1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('is_initial_disbursement', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_transfer', 'is_initial_disbursement')
    # ### end Alembic commands ###
