"""empty message

Revision ID: 1733c4d4c77b
Revises: 5462eb228850
Create Date: 2019-11-17 18:44:09.625124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1733c4d4c77b'
down_revision = '5462eb228850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('exchange_rate', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange', 'exchange_rate')
    # ### end Alembic commands ###
