"""empty message

Revision ID: 1b6b5e7adf0f
Revises: 0fb2f2fc39d8
Create Date: 2019-09-09 12:33:05.586456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6b5e7adf0f'
down_revision = '0fb2f2fc39d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_application', sa.Column('namescan_scan_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc_application', 'namescan_scan_id')
    # ### end Alembic commands ###
