"""empty message

Revision ID: 1c0c947af497
Revises: 5684815413ed
Create Date: 2018-09-11 17:50:58.859722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0c947af497'
down_revision = '5684815413ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('one_time_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'one_time_code')
    # ### end Alembic commands ###
