"""empty message

Revision ID: 1c89fa61f23e
Revises: d1bf5c21d9f3
Create Date: 2019-11-12 14:35:54.039916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c89fa61f23e'
down_revision = 'd1bf5c21d9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_targeting_survey_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'targeting_survey_id')
    op.drop_table('targeting_survey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('targeting_survey_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_targeting_survey_id_fkey', 'user', 'targeting_survey', ['targeting_survey_id'], ['id'])
    op.create_table('targeting_survey',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('number_people_household', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_below_adult_age_household', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_people_women_household', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_people_men_household', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_people_work_household', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('disabilities_household', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('long_term_illnesses_household', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('authorising_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='targeting_survey_pkey')
    )
    # ### end Alembic commands ###
