"""empty message

Revision ID: 1dd6108b2f65
Revises: d7d94595a720
Create Date: 2018-10-18 10:16:22.740432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd6108b2f65'
down_revision = 'd7d94595a720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('transfer_account', 'payable_epoch', existing_type=sa.String(), type=sa.DateTime())
    # op.alter_column('transfer_account', 'user', new_column_name='users')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('transfer_account', 'payable_epoch', existing_type=sa.String(), type=sa.DateTime())
    # op.alter_column('transfer_account', 'users', new_column_name='user')
    # ### end Alembic commands ###
    pass
