"""empty message

Revision ID: 1e8ce90db7d4
Revises: 7580066bfb5c
Create Date: 2019-01-26 13:55:26.776577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8ce90db7d4'
down_revision = '7580066bfb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_image', sa.Column('image_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploaded_image', 'image_type')
    # ### end Alembic commands ###
