"""empty message

Revision ID: 20f02b5081bf
Revises: 5c76f2801635
Create Date: 2019-01-23 13:50:16.213893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f02b5081bf'
down_revision = '5c76f2801635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_address', sa.Column('type', sa.String(), nullable=True))
    op.add_column('blockchain_transaction', sa.Column('message', sa.String(), nullable=True))
    op.add_column('blockchain_transaction', sa.Column('signing_blockchain_address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blockchain_transaction', 'blockchain_address', ['signing_blockchain_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blockchain_transaction', type_='foreignkey')
    op.drop_column('blockchain_transaction', 'signing_blockchain_address_id')
    op.drop_column('blockchain_transaction', 'message')
    op.drop_column('blockchain_address', 'type')
    # ### end Alembic commands ###
