"""empty message

Revision ID: 21b7217d19cf
Revises: 22da69b533f1
Create Date: 2019-10-29 13:21:11.121481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21b7217d19cf'
down_revision = '22da69b533f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_contract', sa.Column('subcontract_address_mapping', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_contract', 'subcontract_address_mapping')
    # ### end Alembic commands ###
