"""empty message

Revision ID: 22da69b533f1
Revises: fbba33e6bd4b
Create Date: 2019-10-27 17:55:49.282634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22da69b533f1'
down_revision = 'fbba33e6bd4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_contract', sa.Column('contract_registry_blockchain_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchange_contract', 'contract_registry_blockchain_address')
    # ### end Alembic commands ###
