"""empty message

Revision ID: 23a26fb14703
Revises: b40055ad9587
Create Date: 2019-10-30 14:08:36.584530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a26fb14703'
down_revision = 'b40055ad9587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('custom_welcome_message_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'custom_welcome_message_key')
    # ### end Alembic commands ###
