"""empty message

Revision ID: 2591b8be0eb8
Revises: 5f4b4c9f586d
Create Date: 2020-01-26 12:28:39.121376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2591b8be0eb8'
down_revision = '5f4b4c9f586d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_ussd_self_sign_up', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_ussd_self_sign_up')
    # ### end Alembic commands ###
