"""Add new disbursement columns

Revision ID: 279b30132f29
Revises: 0f01cb955ea0
Create Date: 2021-01-15 10:45:07.182643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279b30132f29'
down_revision = '0f01cb955ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disbursement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorising_user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('creator_user_id', sa.Integer(), nullable=True),
    sa.Column('search_string', sa.String(), nullable=True),
    sa.Column('search_filter_params', sa.String(), nullable=True),
    sa.Column('include_users', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('exclude_users', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('is_executed', sa.Boolean(), nullable=True),
    sa.Column('_disbursement_amount_wei', sa.Numeric(precision=27), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disbursement_creator_user_id'), 'disbursement', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_disbursement_id'), 'disbursement', ['id'], unique=False)
    op.create_table('disbursement_transfer_account_association_table',
    sa.Column('disbursement_id', sa.Integer(), nullable=True),
    sa.Column('transfer_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disbursement_id'], ['disbursement.id'], ),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['transfer_account.id'], )
    )
    op.create_index(op.f('ix_disbursement_transfer_account_association_table_disbursement_id'), 'disbursement_transfer_account_association_table', ['disbursement_id'], unique=False)
    op.create_index(op.f('ix_disbursement_transfer_account_association_table_transfer_account_id'), 'disbursement_transfer_account_association_table', ['transfer_account_id'], unique=False)
    op.create_table('disbursement_credit_transfer_association_table',
    sa.Column('disbursement_id', sa.Integer(), nullable=True),
    sa.Column('credit_transfer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_transfer_id'], ['credit_transfer.id'], ),
    sa.ForeignKeyConstraint(['disbursement_id'], ['disbursement.id'], )
    )
    op.create_index(op.f('ix_disbursement_credit_transfer_association_table_credit_transfer_id'), 'disbursement_credit_transfer_association_table', ['credit_transfer_id'], unique=False)
    op.create_index(op.f('ix_disbursement_credit_transfer_association_table_disbursement_id'), 'disbursement_credit_transfer_association_table', ['disbursement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disbursement_credit_transfer_association_table_disbursement_id'), table_name='disbursement_credit_transfer_association_table')
    op.drop_index(op.f('ix_disbursement_credit_transfer_association_table_credit_transfer_id'), table_name='disbursement_credit_transfer_association_table')
    op.drop_table('disbursement_credit_transfer_association_table')
    op.drop_index(op.f('ix_disbursement_transfer_account_association_table_transfer_account_id'), table_name='disbursement_transfer_account_association_table')
    op.drop_index(op.f('ix_disbursement_transfer_account_association_table_disbursement_id'), table_name='disbursement_transfer_account_association_table')
    op.drop_table('disbursement_transfer_account_association_table')
    op.drop_index(op.f('ix_disbursement_id'), table_name='disbursement')
    op.drop_index(op.f('ix_disbursement_creator_user_id'), table_name='disbursement')
    op.drop_table('disbursement')
    # ### end Alembic commands ###
