"""empty message

Revision ID: 284952854886
Revises: dcaf48442917
Create Date: 2019-06-17 11:50:46.177592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284952854886'
down_revision = 'dcaf48442917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_TFA_secret', sa.String(length=16), nullable=True))
    op.drop_column('user', 'TFA_secret')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('TFA_secret', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.drop_column('user', '_TFA_secret')
    # ### end Alembic commands ###
