"""Add transfer card usage table

Revision ID: 286d3cf3c133
Revises: 8e010839bc25
Create Date: 2022-07-22 13:18:47.418917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286d3cf3c133'
down_revision = '8e010839bc25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_card_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorising_user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('vendor_transfer_account_id', sa.Integer(), nullable=True),
    sa.Column('transfer_card_id', sa.Integer(), nullable=True),
    sa.Column('credit_transfer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_transfer_id'], ['credit_transfer.id'], ),
    sa.ForeignKeyConstraint(['transfer_card_id'], ['transfer_card.id'], ),
    sa.ForeignKeyConstraint(['vendor_transfer_account_id'], ['transfer_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_card_state')
    # ### end Alembic commands ###
