"""empty message

Revision ID: 2a137ac5d786
Revises: 4953987e98b1
Create Date: 2019-11-28 21:12:29.403985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a137ac5d786'
down_revision = '4953987e98b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('is_ghost', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_account', 'is_ghost')
    # ### end Alembic commands ###
