"""empty message

Revision ID: 2ad53fe91068
Revises: 488e4deed55b
Create Date: 2019-12-20 12:54:27.446577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ad53fe91068'
down_revision = '488e4deed55b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("COMMIT")
    op.execute("ALTER TYPE transfersubtypeenum ADD VALUE 'STANDARD'")

    # # ### end Alembic commands ###


def downgrade():
    pass

#     POSTGRES DOESN'T SUPPORT REMOVING OF ENUMS
#     " Existing values cannot be removed from an enum type, nor can the sort ordering of such values be changed,
#      short of dropping and re-creating the enum type."

