"""empty message

Revision ID: 2b996c8b006b
Revises: 420c0fc5ecf8
Create Date: 2020-03-03 13:01:48.532474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b996c8b006b'
down_revision = '420c0fc5ecf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'initial_disbursement_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('initial_disbursement_amount', sa.REAL(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
