"""empty message

Revision ID: 2c4716931a43
Revises: 7c0e719eccd9
Create Date: 2019-10-18 20:49:39.227852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4716931a43'
down_revision = '7c0e719eccd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('business_usage_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'business_usage_id')
    # ### end Alembic commands ###
