"""empty message

Revision ID: 2cbb3f38576a
Revises: 40f1f3f33f0a
Create Date: 2019-05-02 18:43:13.051917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cbb3f38576a'
down_revision = '40f1f3f33f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_usage', sa.Column('is_cashout', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_usage', 'is_cashout')
    # ### end Alembic commands ###
