"""empty message

Revision ID: 2ccfaa8b79e7
Revises: 2ff46ae4b74c
Create Date: 2019-09-15 13:51:51.315462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ccfaa8b79e7'
down_revision = '2ff46ae4b74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spend_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorising_user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('eth_send_task_id', sa.Integer(), nullable=True),
    sa.Column('approval_task_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('giving_transfer_account_id', sa.Integer(), nullable=True),
    sa.Column('receiving_transfer_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['giving_transfer_account_id'], ['transfer_account.id'], ),
    sa.ForeignKeyConstraint(['receiving_transfer_account_id'], ['transfer_account.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spend_approvals')
    # ### end Alembic commands ###
