"""empty message

Revision ID: 2e27b57df2f6
Revises: a6f67f137e42
Create Date: 2020-01-10 16:12:39.654861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e27b57df2f6'
down_revision = 'a6f67f137e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('_timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', '_timezone')
    # ### end Alembic commands ###
