"""empty message

Revision ID: 2ed5e5423ada
Revises: dadfc046c4cb
Create Date: 2018-11-08 16:05:18.233313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed5e5423ada'
down_revision = 'dadfc046c4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('block', sa.Integer(), nullable=True))
    op.add_column('blockchain_transaction', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_transaction', 'status')
    op.drop_column('blockchain_transaction', 'block')
    # ### end Alembic commands ###
