"""empty message

Revision ID: 326a61cf9fde
Revises: 0d586d339657
Create Date: 2020-02-06 22:15:59.291141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326a61cf9fde'
down_revision = '0d586d339657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sign_up_method', sa.String(), nullable=True))
    op.drop_column('user', 'is_ussd_self_sign_up')
    op.drop_column('user', 'data_sharing_accepted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_ussd_self_sign_up', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('data_sharing_accepted'), sa.BOOLEAN(), autoincrement=False, nullable=True)
    op.drop_column('user', 'sign_up_method')
    # ### end Alembic commands ###
