"""Add card sharding distance

Revision ID: 3386e7f8b71f
Revises: f70402545b60
Create Date: 2020-10-16 15:05:41.834432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3386e7f8b71f'
down_revision = 'f70402545b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('card_shard_distance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'card_shard_distance')
    # ### end Alembic commands ###
