"""empty message

Revision ID: 382ccbdbbb3f
Revises: 21b7217d19cf
Create Date: 2019-10-29 18:28:09.224676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '382ccbdbbb3f'
down_revision = '21b7217d19cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_contract', sa.Column('subexchange_address_mapping', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_exchange_contract_contract_registry_blockchain_address'), 'exchange_contract', ['contract_registry_blockchain_address'], unique=False)
    op.drop_column('exchange_contract', 'subcontract_address_mapping')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_contract', sa.Column('subcontract_address_mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_exchange_contract_contract_registry_blockchain_address'), table_name='exchange_contract')
    op.drop_column('exchange_contract', 'subexchange_address_mapping')
    # ### end Alembic commands ###
