"""Enforce non-nullable required fields for organisation

Revision ID: 3b14e2aff4ea
Revises: 7b3486815759
Create Date: 2021-03-31 10:00:57.648366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b14e2aff4ea'
down_revision = '7b3486815759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation', '_timezone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organisation', '_timezone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
