"""empty message

Revision ID: 3c523b7fe87d
Revises: c457ec750f96
Create Date: 2018-09-25 11:33:47.664046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c523b7fe87d'
down_revision = 'c457ec750f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('payable_period_type', sa.String(), nullable=True),
    sa.Column('payable_period_length', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transfer_account', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer_account', 'transfer_account', ['vendor_id'], ['id'])
    op.drop_column('transfer_account', 'chat_transfer_initialised')
    op.drop_column('transfer_account', '_phone')
    op.drop_column('transfer_account', 'qr_code')
    op.drop_column('transfer_account', 'chat_source_preference')
    op.drop_column('transfer_account', 'facebook_psid')
    op.drop_column('transfer_account', 'nfc_card_id')
    op.drop_column('transfer_account', 'chat_target_account_id')
    op.drop_column('transfer_account', 'pin')
    op.drop_column('transfer_account', 'chat_last_accessed')
    op.drop_column('transfer_account', 'secret')
    op.drop_column('transfer_account', 'chat_prev_pin_failures')
    op.drop_column('transfer_account', 'chat_transfer_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('chat_transfer_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('chat_prev_pin_failures', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('secret', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('chat_last_accessed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('pin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('chat_target_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('nfc_card_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('facebook_psid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('chat_source_preference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('qr_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('chat_transfer_initialised', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transfer_account', type_='foreignkey')
    op.drop_column('transfer_account', 'vendor_id')
    op.drop_table('vendor')
    # ### end Alembic commands ###
