"""empty message

Revision ID: 3ceb7f507cd0
Revises: 925bbebe94bd
Create Date: 2018-10-18 14:34:52.310934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ceb7f507cd0'
down_revision = '925bbebe94bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('added_date', sa.DateTime(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('credit_transfer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_transfer_id'], ['credit_transfer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('public_serial_number', sa.Column('nfc_serial_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_serial_number', 'nfc_serial_number')
    op.drop_table('blockchain_transaction')
    # ### end Alembic commands ###
