"""empty message

Revision ID: 3d146d7e19c4
Revises: 1dd6108b2f65
Create Date: 2018-10-18 10:30:25.725914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d146d7e19c4'
down_revision = '1dd6108b2f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_account', 'payable_epoch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('payable_epoch', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
