"""empty message

Revision ID: 4527fe5c9b99
Revises: 2e2bb6fc17a2
Create Date: 2018-10-10 15:44:28.606361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4527fe5c9b99'
down_revision = '2e2bb6fc17a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_info', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'device_info', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_info', type_='foreignkey')
    op.drop_column('device_info', 'user_id')
    # ### end Alembic commands ###
