"""empty message

Revision ID: 46c46aebbf1c
Revises: 9041b99c155e
Create Date: 2019-07-05 09:49:00.486176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c46aebbf1c'
down_revision = '9041b99c155e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_phone_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_phone_verified')
    # ### end Alembic commands ###
