"""empty message

Revision ID: 47c9e8260c4d
Revises: 92b7f1788e1a
Create Date: 2019-01-29 12:15:23.855825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47c9e8260c4d'
down_revision = '92b7f1788e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('matched_profile_pictures', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'matched_profile_pictures')
    # ### end Alembic commands ###
