"""empty message

Revision ID: 488e4deed55b
Revises: 21a880175a91
Create Date: 2019-12-10 22:40:46.949977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488e4deed55b'
down_revision = '21a880175a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('primary_blockchain_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'primary_blockchain_address')
    # ### end Alembic commands ###
