"""empty message

Revision ID: 4953987e98b1
Revises: 4a118ebf7e0c
Create Date: 2019-11-21 13:03:39.703159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4953987e98b1'
down_revision = '4a118ebf7e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('failed_pin_attempts', sa.Integer(), nullable=True, default=0))
    op.add_column('user', sa.Column('pin_hash', sa.String(), nullable=True))
    op.add_column('user', sa.Column('pin_reset_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pin_reset_tokens')
    op.drop_column('user', 'pin_hash')
    op.drop_column('user', 'failed_pin_attempts')
    # ### end Alembic commands ###
