"""empty message

Revision ID: 49e8a333d285
Revises: d7b89a614ae9
Create Date: 2020-06-02 10:37:49.647260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e8a333d285'
down_revision = 'd7b89a614ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_worker_messages_table_blockchain_task_uuid', table_name='worker_messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_worker_messages_table_blockchain_task_uuid', 'worker_messages', ['blockchain_task_uuid'], unique=False)
    # ### end Alembic commands ###
