"""empty message

Revision ID: 4ad04972665f
Revises: bef055f8c6d6
Create Date: 2019-02-25 15:22:13.809490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad04972665f'
down_revision = 'bef055f8c6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_public_serial_number', sa.String(), nullable=True))
    op.drop_column('user', 'public_serial_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_serial_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', '_public_serial_number')
    # ### end Alembic commands ###
