"""Add ingress/egress

Revision ID: 4edd1383530d
Revises: dd768e99637e
Create Date: 2022-02-04 12:25:55.570962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4edd1383530d'
down_revision = 'dd768e99637e'
branch_labels = None
depends_on = None

fiatrampdirection = sa.Enum('INGRESS', 'EGRESS', name='fiatrampdirection')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    fiatrampdirection.create(op.get_bind(), checkfirst=True)
    op.add_column('fiat_ramp', sa.Column('payment_direction', fiatrampdirection, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiat_ramp', 'payment_direction')
    # ### end Alembic commands ###
