"""Add card metadata to transfer_card_state

Revision ID: 50fa8260cee7
Revises: 286d3cf3c133
Create Date: 2022-07-22 15:43:28.831098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50fa8260cee7'
down_revision = '286d3cf3c133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_card_state', sa.Column('session_number', sa.Integer(), nullable=True))
    op.add_column('transfer_card_state', sa.Column('amount_loaded', sa.Integer(), nullable=True))
    op.add_column('transfer_card_state', sa.Column('amount_deducted', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_card_state', 'session_number')
    op.drop_column('transfer_card_state', 'amount_loaded')
    op.drop_column('transfer_card_state', 'amount_deducted')
    # ### end Alembic commands ###
