"""empty message

Revision ID: 52bda03997d7
Revises: e369fe1c0bb1
Create Date: 2019-10-22 21:58:31.139780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52bda03997d7'
down_revision = 'e369fe1c0bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_exchange_contract_blockchain_address'), 'exchange_contract', ['blockchain_address'], unique=False)
    op.add_column('transfer_account', sa.Column('_balance', sa.BigInteger(), nullable=True))
    op.drop_column('transfer_account', 'balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('balance', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('transfer_account', '_balance')
    op.drop_index(op.f('ix_exchange_contract_blockchain_address'), table_name='exchange_contract')
    # ### end Alembic commands ###
