"""empty message

Revision ID: 534b493a8e6d
Revises: af906681b8b2
Create Date: 2019-10-17 15:14:49.717037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534b493a8e6d'
down_revision = 'af906681b8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorising_user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('to_desired_amount', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('from_token_id', sa.Integer(), nullable=True),
    sa.Column('to_token_id', sa.Integer(), nullable=True),
    sa.Column('from_transfer_id', sa.Integer(), nullable=True),
    sa.Column('to_transfer_id', sa.Integer(), nullable=True),
    sa.Column('blockchain_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_token_id'], ['token.id'], ),
    sa.ForeignKeyConstraint(['from_transfer_id'], ['credit_transfer.id'], ),
    sa.ForeignKeyConstraint(['to_token_id'], ['token.id'], ),
    sa.ForeignKeyConstraint(['to_transfer_id'], ['credit_transfer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorising_user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('blockchain_address', sa.String(), nullable=True),
    sa.Column('transfer_account_id', sa.Integer(), nullable=True),
    sa.Column('reserve_token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reserve_token_id'], ['token.id'], ),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['transfer_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_contract_token_association_table',
    sa.Column('exchange_contract_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_contract_id'], ['exchange_contract.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange_contract_token_association_table')
    op.drop_table('exchange_contract')
    op.drop_table('exchange')
    # ### end Alembic commands ###
