"""empty message

Revision ID: 5462eb228850
Revises: d1bf5c21d9f3
Create Date: 2019-11-17 14:46:23.247966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5462eb228850'
down_revision = 'd1bf5c21d9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('is_master', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'is_master')
    # ### end Alembic commands ###
