"""empty message

Revision ID: 558c9667af5f
Revises: 5b13c102b559
Create Date: 2018-09-02 11:58:22.590670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '558c9667af5f'
down_revision = '5b13c102b559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transfer_account_nfc_card_id_key', 'transfer_account', type_='unique')
    op.drop_constraint('transfer_account_qr_code_key', 'transfer_account', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('transfer_account_qr_code_key', 'transfer_account', ['qr_code'])
    op.create_unique_constraint('transfer_account_nfc_card_id_key', 'transfer_account', ['nfc_card_id'])
    # ### end Alembic commands ###
