"""empty message
Revision ID: 55aefba0b4ba
Revises: 90b392e41d9f
Create Date: 2019-10-30 22:14:15.514284
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55aefba0b4ba'
down_revision = '90b392e41d9f'
branch_labels = None
depends_on = None

transfer_subtype = sa.Enum('DISBURSEMENT', 'RECLAMATION', 'AGENT_IN', 'AGENT_OUT', 'FEE', 'INCENTIVE', name='transfersubtypeenum')
account_type = sa.Enum('USER', 'ORGANISATION', 'FLOAT', 'CONTRACT', name='transferaccounttype')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    transfer_subtype.create(op.get_bind(), checkfirst=False)
    op.add_column('credit_transfer', sa.Column('transfer_subtype', transfer_subtype, nullable=True))
    op.execute('ALTER TABLE credit_transfer ALTER COLUMN transfer_subtype TYPE transfersubtypeenum'
               ' USING transfer_subtype::text::transfersubtypeenum')

    account_type.create(op.get_bind(), checkfirst=False)
    op.add_column('transfer_account', sa.Column('account_type', transfer_subtype, nullable=True))
    op.execute('ALTER TABLE transfer_account ALTER COLUMN account_type TYPE transferaccounttype'
               ' USING account_type::text::transferaccounttype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_account', 'account_type')
    account_type.drop(op.get_bind(), checkfirst=False)

    op.drop_column('credit_transfer', 'transfer_subtype')
    transfer_subtype.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###