"""empty message

Revision ID: 55c919a64930
Revises: 67630b2085b4
Create Date: 2020-06-11 12:56:32.829470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55c919a64930'
down_revision = '67630b2085b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('synchronization_filter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synchronization_filter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('authorising_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('contract_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contract_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_block_synchronized', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filter_parameters', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filter_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='synchronization_filter_pkey')
    )
    # ### end Alembic commands ###
