"""empty message

Revision ID: 5684815413ed
Revises: 65b082beab7b
Create Date: 2018-09-11 11:20:01.330616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5684815413ed'
down_revision = '65b082beab7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pin_to_public_id', sa.Column('PIN', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pin_to_public_id', 'PIN')
    # ### end Alembic commands ###
