"""empty message

Revision ID: 590c08fa2cbd
Revises: dfd50c445eb7
Create Date: 2018-12-01 14:22:48.365468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590c08fa2cbd'
down_revision = 'dfd50c445eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_conversion', sa.Column('usd_equiv', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency_conversion', 'usd_equiv')
    # ### end Alembic commands ###
