"""Unmigrated indexes

Revision ID: 5a6d53ea57c7
Revises: f1d798cd9521
Create Date: 2020-11-19 10:12:38.505351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6d53ea57c7'
down_revision = 'f1d798cd9521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_credit_transfer_blockchain_task_uuid'), 'credit_transfer', ['blockchain_task_uuid'], unique=False)
    op.create_index(op.f('ix_custom_attribute_name'), 'custom_attribute', ['name'], unique=False)
    op.create_index(op.f('ix_exchange_blockchain_task_uuid'), 'exchange', ['blockchain_task_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_blockchain_task_uuid'), table_name='exchange')
    op.drop_index(op.f('ix_custom_attribute_name'), table_name='custom_attribute')
    op.drop_index(op.f('ix_credit_transfer_blockchain_task_uuid'), table_name='credit_transfer')
    # ### end Alembic commands ###
