"""empty message

Revision ID: 5b13c102b559
Revises: 852732027a92
Create Date: 2018-09-02 10:03:34.373163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b13c102b559'
down_revision = '852732027a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_public_transfer_account_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'public_transfer_account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_transfer_account_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_public_transfer_account_id_fkey', 'user', 'transfer_account', ['public_transfer_account_id'], ['qr_code'])
    # ### end Alembic commands ###
