"""empty message

Revision ID: 5c76f2801635
Revises: 9a8dd5b5edbc
Create Date: 2018-12-17 14:50:24.936943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c76f2801635'
down_revision = '9a8dd5b5edbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorising_user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('credit_transfer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_transfer_id'], ['credit_transfer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('chatbot_state', 'source_preference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_state', sa.Column('source_preference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('uploaded_image')
    # ### end Alembic commands ###
