"""empty message

Revision ID: 5cbc24143619
Revises: 9c233f12de2c
Create Date: 2019-09-13 18:33:39.519662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbc24143619'
down_revision = '9c233f12de2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'organisation', ['default_organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'default_organisation_id')
    # ### end Alembic commands ###
