"""empty message

Revision ID: 5d8eaa7b738c
Revises: 488e4deed55b
Create Date: 2019-12-18 10:27:32.346638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8eaa7b738c'
down_revision = '488e4deed55b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_credit_transfer_transfer_type'), 'credit_transfer', ['transfer_type'], unique=False)
    op.create_index(op.f('ix_organisation_is_master'), 'organisation', ['is_master'], unique=False)
    op.create_index(op.f('ix_user__phone'), 'user', ['_phone'], unique=True)
    op.drop_constraint('user__phone_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user__phone_key', 'user', ['_phone'])
    op.drop_index(op.f('ix_user__phone'), table_name='user')
    op.drop_index(op.f('ix_organisation_is_master'), table_name='organisation')
    op.drop_index(op.f('ix_credit_transfer_transfer_type'), table_name='credit_transfer')
    # ### end Alembic commands ###
