"""empty message

Revision ID: 5de7c462a1e6
Revises: e44eb2604c0c
Create Date: 2019-11-04 21:59:14.913293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de7c462a1e6'
down_revision = 'e44eb2604c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'transfer_usage', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer_usage', type_='unique')
    # ### end Alembic commands ###
