"""empty message

Revision ID: 5e14a51b6865
Revises: 1c89fa61f23e
Create Date: 2019-11-12 15:05:10.200341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e14a51b6865'
down_revision = '1c89fa61f23e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'kyc_state')
    op.drop_column('user', 'ap_user_id')
    op.drop_column('user', 'ap_bank_id')
    op.drop_column('user', 'ap_paypal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ap_paypal_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('ap_bank_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('ap_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('kyc_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
