"""empty message

Revision ID: 5f8a06f9e8ac
Revises: 96862ec4ff72
Create Date: 2018-12-03 17:20:37.692213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f8a06f9e8ac'
down_revision = '96862ec4ff72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_state', sa.Column('provider_message_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot_state', 'provider_message_id')
    # ### end Alembic commands ###
