"""empty message

Revision ID: 603694d49e24
Revises: 7a21a56971ca
Create Date: 2019-08-21 17:33:14.359613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603694d49e24'
down_revision = '7a21a56971ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_address', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blockchain_address', 'organisation', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blockchain_address', type_='foreignkey')
    op.drop_column('blockchain_address', 'organisation_id')
    # ### end Alembic commands ###
