"""Adds notes to transfer account

Revision ID: 6488be258421
Revises: 380a71c24bba
Create Date: 2020-11-16 14:03:39.965036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6488be258421'
down_revision = '380a71c24bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_account', 'notes')
    # ### end Alembic commands ###
