"""empty message

Revision ID: 64d2232ac8c2
Revises: 7b8b70ed9516
Create Date: 2018-11-11 12:18:00.318096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d2232ac8c2'
down_revision = '7b8b70ed9516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('transaction_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_transaction', 'transaction_type')
    # ### end Alembic commands ###
