"""empty message

Revision ID: 65b082beab7b
Revises: 902a827bc3e4
Create Date: 2018-09-11 11:19:40.701894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b082beab7b'
down_revision = '902a827bc3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pin_to_public_id', 'PIN')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pin_to_public_id', sa.Column('PIN', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
