"""empty message

Revision ID: 6cd5f7ce121c
Revises: f2e8611809f4
Create Date: 2019-06-27 14:59:04.367030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd5f7ce121c'
down_revision = 'f2e8611809f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorising_user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_transfer_account_association_table',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transfer_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['transfer_account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('organisation_association_table',
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transfer_account_id', sa.Integer(), nullable=True),
    sa.Column('credit_transfer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_transfer_id'], ['credit_transfer.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['transfer_account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('credit_transfer', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'credit_transfer', 'organisation', ['organisation_id'], ['id'])
    op.add_column('transfer_account', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer_account', 'organisation', ['organisation_id'], ['id'])
    op.add_column('user', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_transfer_account_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'organisation', ['organisation_id'], ['id'])
    op.drop_column('user', 'transfer_account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('transfer_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_transfer_account_id_fkey', 'user', 'transfer_account', ['transfer_account_id'], ['id'])
    op.drop_column('user', 'organisation_id')
    op.drop_constraint(None, 'transfer_account', type_='foreignkey')
    op.drop_column('transfer_account', 'organisation_id')
    op.drop_constraint(None, 'credit_transfer', type_='foreignkey')
    op.drop_column('credit_transfer', 'organisation_id')
    op.drop_table('organisation_association_table')
    op.drop_table('user_transfer_account_association_table')
    op.drop_table('organisation')
    # ### end Alembic commands ###
