"""Adding User and Transfer Account Deleted Column

Revision ID: 6d8a938930ff
Revises: b56b01f25e5e
Create Date: 2020-03-27 14:21:32.239493

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6d8a938930ff'
down_revision = 'b56b01f25e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('_deleted', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('_deleted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_deleted')
    op.drop_column('transfer_account', '_deleted')
    # ### end Alembic commands ###
