"""empty message

Revision ID: 6f5d64e77769
Revises: 20f02b5081bf
Create Date: 2019-01-23 17:05:53.945700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5d64e77769'
down_revision = '20f02b5081bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('nonce', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_transaction', 'nonce')
    # ### end Alembic commands ###
