"""Added an initial disbursement column for each organization

Revision ID: 6fb8a4a348f0
Revises: fc2eeba8e8e8
Create Date: 2020-02-16 12:06:06.401147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb8a4a348f0'
down_revision = '326a61cf9fde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('initial_disbursement_amount', sa.Float(precision=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'initial_disbursement_amount')
    # ### end Alembic commands ###
