"""empty message

Revision ID: 7036c1830a21
Revises: 3ceb7f507cd0
Create Date: 2018-10-23 14:00:07.022846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7036c1830a21'
down_revision = '3ceb7f507cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('is_beneficiary', sa.Boolean(), nullable=True))
    op.drop_column('transfer_account', 'lng')
    op.drop_column('transfer_account', '_location')
    op.drop_column('transfer_account', 'lat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('lng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('transfer_account', 'is_beneficiary')
    # ### end Alembic commands ###
