"""Add indexes

Revision ID: 7238af4164b4
Revises: bb92df9cb6e3
Create Date: 2020-10-28 17:45:14.437838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7238af4164b4'
down_revision = 'bb92df9cb6e3'
branch_labels = None
depends_on = None

def index_exists(name):
    connection = op.get_bind()
    result = connection.execute(
        "SELECT exists(SELECT 1 from pg_indexes where indexname = '{}') as ix_exists;"
            .format(name)
    ).first()
    return bool(result.ix_exists)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    index_exists('ix_credit_transfer_created') or op.create_index(op.f('ix_credit_transfer_created'), 'credit_transfer', ['created'], unique=False)
    index_exists('ix_credit_transfer_recipient_blockchain_address_id') or op.create_index(op.f('ix_credit_transfer_recipient_blockchain_address_id'), 'credit_transfer', ['recipient_blockchain_address_id'], unique=False)
    index_exists('ix_credit_transfer_recipient_transfer_account_id') or op.create_index(op.f('ix_credit_transfer_recipient_transfer_account_id'), 'credit_transfer', ['recipient_transfer_account_id'], unique=False)
    index_exists('ix_credit_transfer_recipient_user_id') or op.create_index(op.f('ix_credit_transfer_recipient_user_id'), 'credit_transfer', ['recipient_user_id'], unique=False)
    index_exists('ix_credit_transfer_sender_blockchain_address_id') or op.create_index(op.f('ix_credit_transfer_sender_blockchain_address_id'), 'credit_transfer', ['sender_blockchain_address_id'], unique=False)
    index_exists('ix_credit_transfer_sender_transfer_account_id') or op.create_index(op.f('ix_credit_transfer_sender_transfer_account_id'), 'credit_transfer', ['sender_transfer_account_id'], unique=False)
    index_exists('ix_credit_transfer_transfer_mode') or op.create_index(op.f('ix_credit_transfer_transfer_mode'), 'credit_transfer', ['transfer_mode'], unique=False)
    index_exists('ix_custom_attribute_user_storage_user_id') or op.create_index(op.f('ix_custom_attribute_user_storage_user_id'), 'custom_attribute_user_storage', ['user_id'], unique=False)
    index_exists('ix_transfer_account__balance_wei') or op.create_index(op.f('ix_transfer_account__balance_wei'), 'transfer_account', ['_balance_wei'], unique=False)
    index_exists('ix_transfer_account_account_type') or op.create_index(op.f('ix_transfer_account_account_type'), 'transfer_account', ['account_type'], unique=False)
    index_exists('ix_transfer_account_created') or op.create_index(op.f('ix_transfer_account_created'), 'transfer_account', ['created'], unique=False)
    index_exists('ix_transfer_account_token_id') or op.create_index(op.f('ix_transfer_account_token_id'), 'transfer_account', ['token_id'], unique=False)
    index_exists('ix_user__location') or op.create_index(op.f('ix_user__location'), 'user', ['_location'], unique=False)
    index_exists('ix_user_created') or op.create_index(op.f('ix_user_created'), 'user', ['created'], unique=False)
    index_exists('ix_user_default_organisation_id') or op.create_index(op.f('ix_user_default_organisation_id'), 'user', ['default_organisation_id'], unique=False)
    index_exists('ix_user_default_transfer_account_id') or op.create_index(op.f('ix_user_default_transfer_account_id'), 'user', ['default_transfer_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_default_transfer_account_id'), table_name='user')
    op.drop_index(op.f('ix_user_default_organisation_id'), table_name='user')
    op.drop_index(op.f('ix_user_created'), table_name='user')
    op.drop_index(op.f('ix_user__location'), table_name='user')
    op.drop_index(op.f('ix_transfer_account_token_id'), table_name='transfer_account')
    op.drop_index(op.f('ix_transfer_account_created'), table_name='transfer_account')
    op.drop_index(op.f('ix_transfer_account_account_type'), table_name='transfer_account')
    op.drop_index(op.f('ix_transfer_account__balance_wei'), table_name='transfer_account')
    op.drop_index(op.f('ix_custom_attribute_user_storage_user_id'), table_name='custom_attribute_user_storage')
    op.drop_index(op.f('ix_credit_transfer_transfer_mode'), table_name='credit_transfer')
    op.drop_index(op.f('ix_credit_transfer_sender_transfer_account_id'), table_name='credit_transfer')
    op.drop_index(op.f('ix_credit_transfer_sender_blockchain_address_id'), table_name='credit_transfer')
    op.drop_index(op.f('ix_credit_transfer_recipient_user_id'), table_name='credit_transfer')
    op.drop_index(op.f('ix_credit_transfer_recipient_transfer_account_id'), table_name='credit_transfer')
    op.drop_index(op.f('ix_credit_transfer_recipient_blockchain_address_id'), table_name='credit_transfer')
    op.drop_index(op.f('ix_credit_transfer_created'), table_name='credit_transfer')
    # ### end Alembic commands ###
