"""empty message

Revision ID: 726fad07bc8d
Revises: dc7ba64ef73d
Create Date: 2020-04-23 09:44:58.568615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726fad07bc8d'
down_revision = 'dc7ba64ef73d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('blockchain_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_transfer', 'blockchain_hash')
    # ### end Alembic commands ###
