"""empty message

Revision ID: 74c172d7b711
Revises: 311569eda055
Create Date: 2019-08-28 21:43:32.960083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c172d7b711'
down_revision = '311569eda055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('token_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organisation', 'token', ['token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organisation', type_='foreignkey')
    op.drop_column('organisation', 'token_id')
    # ### end Alembic commands ###
