"""empty message

Revision ID: 7580066bfb5c
Revises: 6f5d64e77769
Create Date: 2019-01-25 16:47:07.631068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7580066bfb5c'
down_revision = '6f5d64e77769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('custom_attributes', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'custom_attributes')
    # ### end Alembic commands ###
