"""empty message

Revision ID: 7583891c4ae5
Revises: 1c0c947af497
Create Date: 2018-09-23 14:13:26.495521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7583891c4ae5'
down_revision = '1c0c947af497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('source_preference', sa.String(), nullable=True),
    sa.Column('transfer_initialised', sa.Boolean(), nullable=True),
    sa.Column('target_account_id', sa.Integer(), nullable=True),
    sa.Column('transfer_amount', sa.Integer(), nullable=True),
    sa.Column('prev_pin_failures', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('public_serial_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_serial_number', sa.String(), nullable=True),
    sa.Column('PIN', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pin_to_public_id')
    op.add_column('user', sa.Column('_is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('_is_subadmin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('_is_superadmin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('chatbot_state_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('nfc_serial_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('public_serial_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('secret', sa.String(), nullable=True))
    op.create_foreign_key(None, 'user', 'chatbot_state', ['chatbot_state_id'], ['id'])
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'is_superadmin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superadmin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'secret')
    op.drop_column('user', 'public_serial_number')
    op.drop_column('user', 'nfc_serial_number')
    op.drop_column('user', 'chatbot_state_id')
    op.drop_column('user', '_is_superadmin')
    op.drop_column('user', '_is_subadmin')
    op.drop_column('user', '_is_admin')
    op.create_table('pin_to_public_id',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('PIN', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pin_to_public_id_pkey')
    )
    op.drop_table('public_serial_number')
    op.drop_table('chatbot_state')
    # ### end Alembic commands ###
