"""empty message

Revision ID: 77be7170b82d
Revises: 86b008b4599e
Create Date: 2019-09-20 16:06:30.160352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77be7170b82d'
down_revision = '86b008b4599e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('feedback_transfer_account_id_fkey', 'feedback', type_='foreignkey')
    op.create_foreign_key(None, 'feedback', 'user', ['user_id'], ['id'])
    op.drop_column('feedback', 'transfer_account_id')
    op.add_column('user', sa.Column('ap_bank_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('ap_paypal_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('ap_user_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('kyc_state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'kyc_state')
    op.drop_column('user', 'ap_user_id')
    op.drop_column('user', 'ap_paypal_id')
    op.drop_column('user', 'ap_bank_id')
    op.add_column('feedback', sa.Column('transfer_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key('feedback_transfer_account_id_fkey', 'feedback', 'transfer_account', ['transfer_account_id'], ['id'])
    op.drop_column('feedback', 'user_id')
    # ### end Alembic commands ###
