"""empty message

Revision ID: 7a21a56971ca
Revises: ad3878bc0030
Create Date: 2019-08-21 17:00:14.420723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a21a56971ca'
down_revision = 'ad3878bc0030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer_account', 'organisation', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer_account', type_='foreignkey')
    op.drop_column('transfer_account', 'organisation_id')
    # ### end Alembic commands ###
