"""Add disbursement state

Revision ID: 7b3486815759
Revises: b57269691a90
Create Date: 2021-03-18 12:26:56.321212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3486815759'
down_revision = 'b57269691a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disbursement', sa.Column('state', sa.String(), nullable=True))
    op.drop_column('disbursement', 'is_executed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disbursement', sa.Column('is_executed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('disbursement', 'state')
    # ### end Alembic commands ###
