"""empty message
Adds exclude option

Revision ID: 7c0b56f6de5e
Revises: 380a71c24bba
Create Date: 2020-11-16 14:42:27.860151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0b56f6de5e'
down_revision = '380a71c24bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('exclude_from_card_balance', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_transfer', 'exclude_from_card_balance')
    # ### end Alembic commands ###
