"""empty message

Revision ID: 7de5d1973128
Revises: 7550bc658dc5
Create Date: 2019-04-28 00:41:48.141992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de5d1973128'
down_revision = '7550bc658dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_transfer', 'transfer_use')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('transfer_use', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
