"""empty message

Adds token column to transfer account

Revision ID: 7edae859c19f
Revises: 2f8c71039480
Create Date: 2020-10-27 11:07:42.928200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7edae859c19f'
down_revision = '2f8c71039480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_card', sa.Column('token_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer_card', 'token', ['token_id'], ['id'])

    op.execute("""
    UPDATE transfer_card
    SET token_id = transfer_account.token_id
    FROM transfer_account
    WHERE transfer_card.transfer_account_id = transfer_account.id;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer_card', type_='foreignkey')
    op.drop_column('transfer_card', 'token_id')
    # ### end Alembic commands ###
