"""empty message

Revision ID: 806ea6b43c96
Revises: ce41ff512059
Create Date: 2020-01-03 18:57:53.600483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806ea6b43c96'
down_revision = 'ce41ff512059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spend_approval', sa.Column('approval_task_uuid', sa.String(), nullable=True))
    op.add_column('spend_approval', sa.Column('eth_send_task_uuid', sa.String(), nullable=True))
    op.drop_column('spend_approval', 'approval_task_id')
    op.drop_column('spend_approval', 'eth_send_task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spend_approval', sa.Column('eth_send_task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('spend_approval', sa.Column('approval_task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('spend_approval', 'eth_send_task_uuid')
    op.drop_column('spend_approval', 'approval_task_uuid')
    # ### end Alembic commands ###
