"""Add filter hiding

Revision ID: 81dbb121f6ec
Revises: f1d798cd9521
Create Date: 2020-11-23 16:08:28.605804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81dbb121f6ec'
down_revision = 'f1d798cd9521'
branch_labels = None
depends_on = None

metricsvisibility = sa.Enum('SENDER', 'RECIPIENT', 'SENDER_AND_RECIPIENT', 'HIDDEN', name='metricsvisibility')

def upgrade():
    metricsvisibility.create(op.get_bind(), checkfirst=False)

    op.add_column('custom_attribute', sa.Column('filter_visibility', metricsvisibility, nullable=True))
    op.add_column('custom_attribute', sa.Column('group_visibility', metricsvisibility, nullable=True))
    op.execute("UPDATE custom_attribute SET filter_visibility='SENDER_AND_RECIPIENT'")
    op.execute("UPDATE custom_attribute SET group_visibility='SENDER_AND_RECIPIENT'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_attribute', 'group_visibility')
    op.drop_column('custom_attribute', 'filter_visibility')
    # ### end Alembic commands ###
