"""empty message

Revision ID: 852732027a92
Revises: 7da32d18103f
Create Date: 2018-09-02 09:50:30.601995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852732027a92'
down_revision = '7da32d18103f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'transfer_account', ['nfc_card_id'])
    op.create_unique_constraint(None, 'transfer_account', ['qr_code'])
    op.add_column('user', sa.Column('public_transfer_account_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'user', 'transfer_account', ['public_transfer_account_id'], ['qr_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'public_transfer_account_id')
    op.drop_constraint(None, 'transfer_account', type_='unique')
    op.drop_constraint(None, 'transfer_account', type_='unique')
    # ### end Alembic commands ###
