"""empty message

Revision ID: 8671d3d59af5
Revises: 7036c1830a21
Create Date: 2018-10-23 14:08:00.097205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8671d3d59af5'
down_revision = '7036c1830a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_location', sa.String(), nullable=True))
    op.add_column('user', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lng')
    op.drop_column('user', 'lat')
    op.drop_column('user', '_location')
    # ### end Alembic commands ###
