"""Adding Display Decimals

Revision ID: 8a9941c54185
Revises: 984d7e9c50af
Create Date: 2020-05-04 10:15:39.804429

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8a9941c54185'
down_revision = '984d7e9c50af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('display_decimals', sa.Integer(), nullable=True))

    # Updates all existing tokens to default to display_decimals = 2
    op.execute("UPDATE token SET display_decimals = 2 WHERE display_decimals is NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'display_decimals')
    # ### end Alembic commands ###
