"""empty message

Revision ID: 8d672062eb10
Revises: 35aa30ce8a33
Create Date: 2019-10-18 14:07:16.583295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d672062eb10'
down_revision = '35aa30ce8a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_reset_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_reset_tokens')
    # ### end Alembic commands ###
