"""Add disbursement completion status

Revision ID: 8e010839bc25
Revises: 00e04688706c
Create Date: 2022-05-17 15:08:59.660954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e010839bc25'
down_revision = '00e04688706c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disbursement', sa.Column('completion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disbursement', 'completion')
    # ### end Alembic commands ###
