"""empty message

Revision ID: 9041b99c155e
Revises: 6cd5f7ce121c
Create Date: 2019-07-02 16:20:56.784478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9041b99c155e'
down_revision = '6cd5f7ce121c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_is_sempo_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_is_sempo_admin')
    # ### end Alembic commands ###
