"""empty message

Revision ID: 90c5265e5606
Revises: 214ddfc0996c
Create Date: 2019-07-29 10:39:40.003215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c5265e5606'
down_revision = '214ddfc0996c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_application', sa.Column('kyc_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc_application', 'kyc_attempts')
    # ### end Alembic commands ###
