"""empty message

Revision ID: 9143b0501895
Revises: 2e27b57df2f6
Create Date: 2020-01-15 16:02:08.259773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9143b0501895'
down_revision = '2e27b57df2f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_filter', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('saved_filter', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'saved_filter', 'organisation', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_filter', type_='foreignkey')
    op.drop_column('saved_filter', 'organisation_id')
    op.drop_column('saved_filter', 'is_public')
    # ### end Alembic commands ###
