"""empty message

Revision ID: 92669911da26
Revises: 979cfb3ed5df
Create Date: 2019-06-18 16:35:58.089116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92669911da26'
down_revision = '979cfb3ed5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_TFA_secret')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_TFA_secret', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
