"""empty message

Revision ID: 92b7f1788e1a
Revises: 5fa801411a7a
Create Date: 2019-01-29 08:47:23.191822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b7f1788e1a'
down_revision = '5fa801411a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploaded_image', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'uploaded_image', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_image', type_='foreignkey')
    op.drop_column('uploaded_image', 'user_id')
    # ### end Alembic commands ###
