"""empty message

Revision ID: 946a53a419be
Revises: 2a137ac5d786
Create Date: 2019-12-07 15:39:16.360594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946a53a419be'
down_revision = '2a137ac5d786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('is_ghost', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_account', 'is_ghost')
    # ### end Alembic commands ###
