"""empty message

Revision ID: 94c98286e9e1
Revises: d0a60c8c98f8
Create Date: 2018-10-01 16:38:21.445909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c98286e9e1'
down_revision = 'd0a60c8c98f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deactivated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deactivated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
