"""empty message

Revision ID: 96862ec4ff72
Revises: 590c08fa2cbd
Create Date: 2018-12-01 14:36:07.525877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96862ec4ff72'
down_revision = '590c08fa2cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_conversion', sa.Column('rate', sa.Float(), nullable=True))
    op.drop_column('currency_conversion', 'usd_equiv')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_conversion', sa.Column('usd_equiv', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('currency_conversion', 'rate')
    # ### end Alembic commands ###
