"""Add disbursement label

Revision ID: 96c591a96957
Revises: 7b3486815759
Create Date: 2021-03-22 16:36:30.882542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c591a96957'
down_revision = '7b3486815759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disbursement', sa.Column('label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disbursement', 'label')
    # ### end Alembic commands ###
