"""Empty migration - incorrect changes identified by alembic
Revision ID: 98b88b5e4fcf
Revises: 279b30132f29
Create Date: 2021-02-15 15:05:57.430038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98b88b5e4fcf'
down_revision = '279b30132f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass