"""empty message

Revision ID: 9a0ec8ac3881
Revises: f8ce3abf47fb
Create Date: 2021-04-08 13:17:55.036455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0ec8ac3881'
down_revision = 'f8ce3abf47fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disbursement_approver_user_association_table',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('disbursement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disbursement_id'], ['disbursement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_index(op.f('ix_disbursement_approver_user_association_table_disbursement_id'), 'disbursement_approver_user_association_table', ['disbursement_id'], unique=False)
    op.create_index(op.f('ix_disbursement_approver_user_association_table_user_id'), 'disbursement_approver_user_association_table', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disbursement_approver_user_association_table')
    # ### end Alembic commands ###
