"""empty message

Revision ID: 9a0ec8ac3881
Revises: f8ce3abf47fb
Create Date: 2021-04-08 13:17:55.036455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a0ec8ac3881'
down_revision = 'f8ce3abf47fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disbursement_approver_user_association_table',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('disbursement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disbursement_id'], ['disbursement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_index(op.f('ix_disbursement_approver_user_association_table_disbursement_id'), 'disbursement_approver_user_association_table', ['disbursement_id'], unique=False)
    op.create_index(op.f('ix_disbursement_approver_user_association_table_user_id'), 'disbursement_approver_user_association_table', ['user_id'], unique=False)
    op.create_index(op.f('ix_custom_attribute_filter_visibility'), 'custom_attribute', ['filter_visibility'], unique=False)
    op.create_index(op.f('ix_custom_attribute_group_visibility'), 'custom_attribute', ['group_visibility'], unique=False)
    op.drop_index('trgm_first_name', table_name='user')
    op.drop_index('trgm_last_name', table_name='user')
    op.drop_index('trgm_location', table_name='user')
    op.drop_index('trgm_phone', table_name='user')
    op.drop_index('trgm_primary_blockchain_address', table_name='user')
    op.drop_index('trgm_public_serial_number', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('trgm_public_serial_number', 'user', ['_public_serial_number'], unique=False)
    op.create_index('trgm_primary_blockchain_address', 'user', ['primary_blockchain_address'], unique=False)
    op.create_index('trgm_phone', 'user', ['_phone'], unique=False)
    op.create_index('trgm_location', 'user', ['_location'], unique=False)
    op.create_index('trgm_last_name', 'user', ['last_name'], unique=False)
    op.create_index('trgm_first_name', 'user', ['first_name'], unique=False)
    op.drop_index(op.f('ix_custom_attribute_group_visibility'), table_name='custom_attribute')
    op.drop_index(op.f('ix_custom_attribute_filter_visibility'), table_name='custom_attribute')
    op.drop_index(op.f('ix_disbursement_approver_user_association_table_user_id'), table_name='disbursement_approver_user_association_table')
    op.drop_index(op.f('ix_disbursement_approver_user_association_table_disbursement_id'), table_name='disbursement_approver_user_association_table')
    op.drop_table('disbursement_approver_user_association_table')
    # ### end Alembic commands ###
