"""empty message

Revision ID: 9a8dd5b5edbc
Revises: 5f8a06f9e8ac
Create Date: 2018-12-04 13:05:53.367605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8dd5b5edbc'
down_revision = '5f8a06f9e8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_state', sa.Column('target_user_id', sa.Integer(), nullable=True))
    op.drop_column('chatbot_state', 'target_account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_state', sa.Column('target_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('chatbot_state', 'target_user_id')
    # ### end Alembic commands ###
