"""empty message

Revision ID: 9ace61e2ea79
Revises: 64a9c67c226d
Create Date: 2019-11-08 12:44:24.007933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ace61e2ea79'
down_revision = '64a9c67c226d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user', 'transfer_usage', ['business_usage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    # ### end Alembic commands ###
