"""empty message

Revision ID: 9c233f12de2c
Revises: f695fffd9dca
Create Date: 2019-09-13 17:19:57.020856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c233f12de2c'
down_revision = 'f695fffd9dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('org_level_transfer_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_org_level_account", 'organisation', 'transfer_account', ['org_level_transfer_account_id'], ['id'])
    op.drop_constraint('transfer_account_owning_organisation_id_fkey', 'transfer_account', type_='foreignkey')
    op.drop_column('transfer_account', 'owning_organisation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('owning_organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transfer_account_owning_organisation_id_fkey', 'transfer_account', 'organisation', ['owning_organisation_id'], ['id'])
    op.drop_constraint("fk_org_level_account", 'organisation', type_='foreignkey')
    op.drop_column('organisation', 'org_level_transfer_account_id')
    # ### end Alembic commands ###
