"""empty message

Revision ID: 9c4a43f3a227
Revises: 24f943b464ae
Create Date: 2019-04-13 10:23:37.986428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4a43f3a227'
down_revision = '24f943b464ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('has_output_txn', sa.Boolean(), nullable=True))
    op.add_column('blockchain_transaction', sa.Column('is_bitcoin', sa.Boolean(), nullable=True))
    op.add_column('credit_transfer', sa.Column('uuid', sa.String(), nullable=True))
    op.add_column('transfer_card', sa.Column('_amount_loaded', sa.Integer(), nullable=True))
    op.add_column('transfer_card', sa.Column('amount_loaded_signature', sa.String(), nullable=True))
    op.add_column('transfer_card', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer_card', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('_public_serial_number', sa.String(), nullable=True))
    op.drop_column('user', 'public_serial_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_serial_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', '_public_serial_number')
    op.drop_constraint(None, 'transfer_card', type_='foreignkey')
    op.drop_column('transfer_card', 'user_id')
    op.drop_column('transfer_card', 'amount_loaded_signature')
    op.drop_column('transfer_card', '_amount_loaded')
    op.drop_column('credit_transfer', 'uuid')
    op.drop_column('blockchain_transaction', 'is_bitcoin')
    op.drop_column('blockchain_transaction', 'has_output_txn')
    # ### end Alembic commands ###
