"""empty message

Revision ID: 9ce32573d450
Revises: 3500c08573ff
Create Date: 2020-05-01 19:30:30.882495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce32573d450'
down_revision = '3500c08573ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_organisation_association_table_credit_transfer_id'), 'organisation_association_table', ['credit_transfer_id'], unique=False)
    op.create_index(op.f('ix_organisation_association_table_organisation_id'), 'organisation_association_table', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_organisation_association_table_transfer_account_id'), 'organisation_association_table', ['transfer_account_id'], unique=False)
    op.create_index(op.f('ix_organisation_association_table_user_id'), 'organisation_association_table', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_transfer_account_association_table_transfer_account_id'), 'user_transfer_account_association_table', ['transfer_account_id'], unique=False)
    op.create_index(op.f('ix_user_transfer_account_association_table_user_id'), 'user_transfer_account_association_table', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_transfer_account_association_table_user_id'), table_name='user_transfer_account_association_table')
    op.drop_index(op.f('ix_user_transfer_account_association_table_transfer_account_id'), table_name='user_transfer_account_association_table')
    op.drop_index(op.f('ix_organisation_association_table_user_id'), table_name='organisation_association_table')
    op.drop_index(op.f('ix_organisation_association_table_transfer_account_id'), table_name='organisation_association_table')
    op.drop_index(op.f('ix_organisation_association_table_organisation_id'), table_name='organisation_association_table')
    op.drop_index(op.f('ix_organisation_association_table_credit_transfer_id'), table_name='organisation_association_table')
    # ### end Alembic commands ###
