"""empty message

Revision ID: 9d90173194c7
Revises: 9fce58914903
Create Date: 2019-12-21 11:48:09.282992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d90173194c7'
down_revision = '9fce58914903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cashout_authorised')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cashout_authorised', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
