"""empty message

Revision ID: 9dd5ac2ea072
Revises: c1bae50735e8
Create Date: 2018-10-01 16:04:31.473967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd5ac2ea072'
down_revision = 'c1bae50735e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_whitelist', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('email_whitelist', 'item')
    op.add_column('user', sa.Column('is_deactiviated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deactiviated')
    op.add_column('email_whitelist', sa.Column('item', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('email_whitelist', 'email')
    # ### end Alembic commands ###
