"""empty message

Revision ID: 9e8f04ce938b
Revises: c9db3658816a
Create Date: 2019-09-15 21:52:59.001472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8f04ce938b'
down_revision = 'c9db3658816a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('blockchain_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_account', 'blockchain_address')
    # ### end Alembic commands ###
