"""empty message

Revision ID: 9fce58914903
Revises: 5d8eaa7b738c
Create Date: 2019-12-19 23:06:05.147751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fce58914903'
down_revision = '5d8eaa7b738c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_application', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'kyc_application', 'organisation', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kyc_application', type_='foreignkey')
    op.drop_column('kyc_application', 'organisation_id')
    # ### end Alembic commands ###
