"""empty message

Revision ID: a444c06ff950
Revises: 5e14a51b6865
Create Date: 2019-11-20 14:17:37.860854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a444c06ff950'
down_revision = '5e14a51b6865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer_card', 'public_serial_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_transfer_card_public_serial_number'), 'transfer_card', ['public_serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_card_public_serial_number'), table_name='transfer_card')
    op.alter_column('transfer_card', 'public_serial_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
