"""empty message

Revision ID: a6f67f137e42
Revises: 21b185d7a27f
Create Date: 2020-01-07 18:21:31.745176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f67f137e42'
down_revision = '21b185d7a27f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('seen_latest_terms', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'seen_latest_terms')
    # ### end Alembic commands ###
