"""empty message

Revision ID: a993cfbb3233
Revises: 463ddd874cb8
Create Date: 2020-02-21 12:05:42.294568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a993cfbb3233'
down_revision = '463ddd874cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('_default_disbursement_wei', sa.Numeric(precision=27), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', '_default_disbursement_wei')
    # ### end Alembic commands ###
