"""
Adding transfer card to credit transfer table and adding offset amount

Revision ID: a9d07f761fc8
Revises: f1d798cd9521
Create Date: 2020-11-24 17:54:57.349179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d07f761fc8'
down_revision = 'f1d798cd9521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('sender_transfer_card_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_credit_transfer_sender_transfer_card_id'), 'credit_transfer', ['sender_transfer_card_id'], unique=False)
    op.create_foreign_key('credit_transfer_transfer_card_fkey', 'credit_transfer', 'transfer_card', ['sender_transfer_card_id'], ['id'])
    op.add_column('transfer_card', sa.Column('_amount_offset', sa.Integer(), nullable=True))

    # For standard payments, assumes all existing payments have come from the card currently held by the sender
    # by setting all of the sender_transfer_card_id's on the credit transfer to that belonging to sender
    op.execute("""
        WITH cte as (
            SELECT credit_transfer.id as transfer_id, card.id as card_id from credit_transfer
              INNER JOIN transfer_card card
                ON credit_transfer.sender_transfer_account_id = card.transfer_account_id
        )
        UPDATE credit_transfer SET sender_transfer_card_id=cte.card_id
        FROM cte
        WHERE credit_transfer.id = cte.transfer_id AND transfer_subtype='STANDARD'
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_card', '_amount_offset')
    op.drop_constraint('credit_transfer_transfer_card_fkey', 'credit_transfer', type_='foreignkey')
    op.drop_index(op.f('ix_credit_transfer_sender_transfer_card_id'), table_name='credit_transfer')
    op.drop_column('credit_transfer', 'sender_transfer_card_id')
    # ### end Alembic commands ###
