"""
Adding transfer card to credit transfer table and adding offset amount

Revision ID: a9d07f761fc8
Revises: f1d798cd9521
Create Date: 2020-11-24 17:54:57.349179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d07f761fc8'
down_revision = 'f1d798cd9521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('transfer_card_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_credit_transfer_transfer_card_id'), 'credit_transfer', ['transfer_card_id'], unique=False)
    op.create_foreign_key('credit_transfer_transfer_card_fkey', 'credit_transfer', 'transfer_card', ['transfer_card_id'], ['id'])
    op.add_column('transfer_card', sa.Column('amount_offset', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_card', 'amount_offset')
    op.drop_constraint('credit_transfer_transfer_card_fkey', 'credit_transfer', type_='foreignkey')
    op.drop_index(op.f('ix_credit_transfer_transfer_card_id'), table_name='credit_transfer')
    op.drop_column('credit_transfer', 'transfer_card_id')
    # ### end Alembic commands ###
