"""Add notes to disbursement

Revision ID: aaca2fa51ea0
Revises: 7e2d2b201c80
Create Date: 2021-04-23 13:15:51.365674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaca2fa51ea0'
down_revision = '7e2d2b201c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disbursement', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disbursement', 'notes')
    # ### end Alembic commands ###
