"""empty message

Revision ID: abf824df9ae6
Revises: eb57e7df329a
Create Date: 2018-11-01 00:38:41.200032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf824df9ae6'
down_revision = 'eb57e7df329a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('foo', sa.String(), nullable=True))
    op.alter_column('transfer_account', 'balance', existing_type=sa.Integer(), type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'foo')
    op.alter_column('transfer_account', 'balance', existing_type=sa.BigInteger(), type_=sa.Integer())
    # ### end Alembic commands ###
