"""empty message

Revision ID: ad3878bc0030
Revises: 90c5265e5606
Create Date: 2019-08-21 16:49:25.638077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3878bc0030'
down_revision = '90c5265e5606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('credit_transfer_organisation_id_fkey', 'credit_transfer', type_='foreignkey')
    op.drop_column('credit_transfer', 'organisation_id')
    op.drop_constraint('transfer_account_organisation_id_fkey', 'transfer_account', type_='foreignkey')
    op.drop_column('transfer_account', 'organisation_id')
    op.drop_constraint('user_organisation_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'organisation_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_organisation_id_fkey', 'user', 'organisation', ['organisation_id'], ['id'])
    op.add_column('transfer_account', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transfer_account_organisation_id_fkey', 'transfer_account', 'organisation', ['organisation_id'], ['id'])
    op.add_column('credit_transfer', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('credit_transfer_organisation_id_fkey', 'credit_transfer', 'organisation', ['organisation_id'], ['id'])
    # ### end Alembic commands ###
