"""empty message

Revision ID: af132af7e8a8
Revises: ff11abbef524
Create Date: 2019-03-03 19:12:00.503240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af132af7e8a8'
down_revision = 'ff11abbef524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('has_output_txn', sa.Boolean(), nullable=True))
    op.drop_column('blockchain_transaction', 'btc_spend_txn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('btc_spend_txn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blockchain_transaction', 'has_output_txn')
    # ### end Alembic commands ###
