"""empty message

Revision ID: afdbf2c8d633
Revises: 0f01cb955ea0
Create Date: 2021-01-25 17:44:18.581566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdbf2c8d633'
down_revision = '0f01cb955ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_custom_attribute_filter_visibility'), 'custom_attribute', ['filter_visibility'], unique=False)
    op.create_index(op.f('ix_custom_attribute_group_visibility'), 'custom_attribute', ['group_visibility'], unique=False)
    op.add_column('transfer_card', sa.Column('_is_disabled', sa.Boolean(), nullable=True))
    op.drop_index('trgm_first_name', table_name='user')
    op.drop_index('trgm_last_name', table_name='user')
    op.drop_index('trgm_location', table_name='user')
    op.drop_index('trgm_phone', table_name='user')
    op.drop_index('trgm_primary_blockchain_address', table_name='user')
    op.drop_index('trgm_public_serial_number', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('trgm_public_serial_number', 'user', ['_public_serial_number'], unique=False)
    op.create_index('trgm_primary_blockchain_address', 'user', ['primary_blockchain_address'], unique=False)
    op.create_index('trgm_phone', 'user', ['_phone'], unique=False)
    op.create_index('trgm_location', 'user', ['_location'], unique=False)
    op.create_index('trgm_last_name', 'user', ['last_name'], unique=False)
    op.create_index('trgm_first_name', 'user', ['first_name'], unique=False)
    op.drop_column('transfer_card', '_is_disabled')
    op.drop_index(op.f('ix_custom_attribute_group_visibility'), table_name='custom_attribute')
    op.drop_index(op.f('ix_custom_attribute_filter_visibility'), table_name='custom_attribute')
    # ### end Alembic commands ###
