"""
Adds transfer card _is_disabled boolean

Revision ID: afdbf2c8d633
Revises: 0f01cb955ea0
Create Date: 2021-01-25 17:44:18.581566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afdbf2c8d633'
down_revision = '0f01cb955ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_card', sa.Column('_is_disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_card', '_is_disabled')
    # ### end Alembic commands ###
