"""empty message

Revision ID: b13e56673261
Revises: 4ad04972665f
Create Date: 2019-02-28 16:32:52.671071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13e56673261'
down_revision = '4ad04972665f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_transfer', 'uuid')
    # ### end Alembic commands ###
