"""empty message

Revision ID: b167606c5081
Revises: 8671d3d59af5
Create Date: 2018-10-23 14:08:29.282086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b167606c5081'
down_revision = '8671d3d59af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('resolution_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_transfer', 'resolution_message')
    # ### end Alembic commands ###
