"""empty message

Revision ID: b21655260b53
Revises: dfaa9f19e75c
Create Date: 2020-01-06 11:25:50.329757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b21655260b53'
down_revision = 'dfaa9f19e75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_application', sa.Column('other_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc_application', 'other_data')
    # ### end Alembic commands ###
