"""empty message

Revision ID: b40055ad9587
Revises: 778e1348250b
Create Date: 2019-10-30 13:14:30.883079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40055ad9587'
down_revision = '778e1348250b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ussd_menus', sa.Column('display_key', sa.String(), nullable=False))
    op.drop_column('ussd_menus', 'display_text_sw')
    op.drop_column('ussd_menus', 'display_text_en')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ussd_menus', sa.Column('display_text_en', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('ussd_menus', sa.Column('display_text_sw', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('ussd_menus', 'display_key')
    # ### end Alembic commands ###
