"""empty message

Revision ID: b56b01f25e5e
Revises: c709ae4679ad
Create Date: 2020-03-02 15:09:46.109061

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b56b01f25e5e'
down_revision = 'c709ae4679ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('_country_code', sa.String(), nullable=True))
    op.add_column('organisation', sa.Column('_default_disbursement_wei', sa.Numeric(precision=27), nullable=True))
    op.add_column('organisation', sa.Column('require_transfer_card', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'require_transfer_card')
    op.drop_column('organisation', '_default_disbursement_wei')
    op.drop_column('organisation', '_country_code')
    # ### end Alembic commands ###
