"""empty message

Revision ID: b8f99367e8fa
Revises: 27fe12b01d66
Create Date: 2019-06-19 10:16:51.472651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f99367e8fa'
down_revision = '27fe12b01d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_TFA_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_TFA_enabled')
    # ### end Alembic commands ###
