"""empty message

Revision ID: b9ef03983336
Revises: 
Create Date: 2018-08-13 10:50:56.384784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ef03983336'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('custom_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_whitelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('item', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('facebook_psid', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('pin', sa.String(), nullable=True),
    sa.Column('nfc_card_id', sa.String(), nullable=True),
    sa.Column('qr_code', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('chat_source_preference', sa.String(), nullable=True),
    sa.Column('chat_transfer_initialised', sa.Boolean(), nullable=True),
    sa.Column('chat_target_account_id', sa.Integer(), nullable=True),
    sa.Column('chat_transfer_amount', sa.Integer(), nullable=True),
    sa.Column('chat_prev_pin_failures', sa.Integer(), nullable=True),
    sa.Column('chat_last_accessed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blockchain_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('encoded_private_key', sa.String(), nullable=True),
    sa.Column('transfer_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['transfer_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_transfer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('resolved_date', sa.DateTime(), nullable=True),
    sa.Column('transfer_amount', sa.Integer(), nullable=True),
    sa.Column('transfer_type', sa.Enum('PAYMENT', 'DISBURSEMENT', 'WITHDRAWAL', name='transfertypeenum'), nullable=True),
    sa.Column('transfer_mode', sa.Enum('NFC', 'SMS', 'QR', 'INTERNAL', 'OTHER', name='transfermodeenum'), nullable=True),
    sa.Column('transfer_status', sa.Enum('PENDING', 'COMPLETE', 'REJECTED', name='transferstatusenum'), nullable=True),
    sa.Column('transfer_use', sa.String(), nullable=True),
    sa.Column('blockchain_transaction_hash', sa.String(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['transfer_account.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['transfer_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_vendor', sa.Boolean(), nullable=True),
    sa.Column('is_beneficiary', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=True),
    sa.Column('transfer_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['transfer_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('credit_transfer')
    op.drop_table('blockchain_address')
    op.drop_table('transfer_account')
    op.drop_table('email_whitelist')
    op.drop_table('custom_settings')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
