"""empty message

Revision ID: bb9a5ada06dd
Revises: 5f4b4c9f586d
Create Date: 2020-01-24 11:34:52.405876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9a5ada06dd'
down_revision = '5f4b4c9f586d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_whitelist', sa.Column('sent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_whitelist', 'sent')
    # ### end Alembic commands ###
