"""Refactor audit history

Revision ID: bc84f5f02e9c
Revises: ded3fa45363a
Create Date: 2021-12-02 12:54:17.830708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc84f5f02e9c'
down_revision = 'ded3fa45363a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_history', sa.Column('foreign_id', sa.Integer(), nullable=True))
    op.add_column('audit_history', sa.Column('foreign_table_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_audit_history_foreign_id'), 'audit_history', ['foreign_id'], unique=False)
    op.create_index(op.f('ix_audit_history_foreign_table_name'), 'audit_history', ['foreign_table_name'], unique=False)
    op.drop_constraint('audit_history_transfer_account_id_fkey', 'audit_history', type_='foreignkey')
    op.drop_constraint('audit_history_user_id_fkey', 'audit_history', type_='foreignkey')
    op.drop_column('audit_history', 'transfer_account_id')
    op.drop_column('audit_history', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_history', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('audit_history', sa.Column('transfer_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('audit_history_user_id_fkey', 'audit_history', 'user', ['user_id'], ['id'])
    op.create_foreign_key('audit_history_transfer_account_id_fkey', 'audit_history', 'transfer_account', ['transfer_account_id'], ['id'])
    op.drop_index(op.f('ix_audit_history_foreign_table_name'), table_name='audit_history')
    op.drop_index(op.f('ix_audit_history_foreign_id'), table_name='audit_history')
    op.drop_column('audit_history', 'foreign_table_name')
    op.drop_column('audit_history', 'foreign_id')
    # ### end Alembic commands ###
