"""empty message

Revision ID: bef055f8c6d6
Revises: 4688c879cae3
Create Date: 2019-02-25 14:54:10.284547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef055f8c6d6'
down_revision = '4688c879cae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_card', sa.Column('_amount_loaded', sa.Integer(), nullable=True))
    op.add_column('transfer_card', sa.Column('amount_loaded_signature', sa.String(), nullable=True))
    op.add_column('transfer_card', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer_card', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer_card', type_='foreignkey')
    op.drop_column('transfer_card', 'user_id')
    op.drop_column('transfer_card', 'amount_loaded_signature')
    op.drop_column('transfer_card', '_amount_loaded')
    # ### end Alembic commands ###
