"""empty message

Revision ID: c1bae50735e8
Revises: 3c523b7fe87d
Create Date: 2018-09-25 14:19:33.523212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1bae50735e8'
down_revision = '3c523b7fe87d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor')
    op.add_column('transfer_account', sa.Column('is_vendor', sa.Boolean(), nullable=True))
    op.add_column('transfer_account', sa.Column('name', sa.String(), nullable=True))
    op.add_column('transfer_account', sa.Column('payable_epoch', sa.String(), nullable=True))
    op.add_column('transfer_account', sa.Column('payable_period_length', sa.Integer(), nullable=True))
    op.add_column('transfer_account', sa.Column('payable_period_type', sa.String(), nullable=True))
    op.drop_constraint('transfer_account_vendor_id_fkey', 'transfer_account', type_='foreignkey')
    op.drop_column('transfer_account', 'last_name')
    op.drop_column('transfer_account', 'first_name')
    op.drop_column('transfer_account', 'vendor_id')
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.add_column('transfer_account', sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transfer_account', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('transfer_account_vendor_id_fkey', 'transfer_account', 'transfer_account', ['vendor_id'], ['id'])
    op.drop_column('transfer_account', 'payable_period_type')
    op.drop_column('transfer_account', 'payable_period_length')
    op.drop_column('transfer_account', 'payable_epoch')
    op.drop_column('transfer_account', 'name')
    op.drop_column('transfer_account', 'is_vendor')
    op.create_table('vendor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payable_period_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payable_period_length', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vendor_pkey')
    )
    # ### end Alembic commands ###
