"""empty message

Revision ID: c392929a91cc
Revises: a5b2eef92bfb
Create Date: 2019-07-22 13:56:24.940746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c392929a91cc'
down_revision = 'a5b2eef92bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_whitelist', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'email_whitelist', 'organisation', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email_whitelist', type_='foreignkey')
    op.drop_column('email_whitelist', 'organisation_id')
    # ### end Alembic commands ###
