"""Add minimum vendor payout withdrawal

Revision ID: c43a0ce4d15d
Revises: 3de8e29dd5c4
Create Date: 2020-10-30 11:30:31.029332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43a0ce4d15d'
down_revision = '3de8e29dd5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('_minimum_vendor_payout_withdrawal_wei', sa.Numeric(precision=27), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', '_minimum_vendor_payout_withdrawal_wei')
    # ### end Alembic commands ###
