"""empty message

Revision ID: c457ec750f96
Revises: 0a0e0257f303
Create Date: 2018-09-23 19:18:48.372392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c457ec750f96'
down_revision = '0a0e0257f303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_is_supervendor', sa.Boolean(), nullable=True))
    op.drop_column('user', '_is_subvendor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_is_subvendor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', '_is_supervendor')
    # ### end Alembic commands ###
