"""empty message

Revision ID: c751b5d5bad9
Revises: 4a5e2904e3f1
Create Date: 2018-09-23 19:05:35.401810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c751b5d5bad9'
down_revision = '4a5e2904e3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_is_supervendor', sa.Boolean(), nullable=True))
    op.drop_column('user', '_is_subvendor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_is_subvendor', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', '_is_supervendor')
    # ### end Alembic commands ###
