"""Creates float accounts for tokens

Revision ID: c7b0c1d52ae6
Revises: 8a5d59bb1089
Create Date: 2020-09-22 13:41:33.024673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b0c1d52ae6'
down_revision = '8a5d59bb1089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('float_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key('float_account_relationship', 'token', 'transfer_account', ['float_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'float_account_id')
    # ### end Alembic commands ###
