"""Ensure indexes on IDs

Revision ID: c8395e165794
Revises: 5a6d53ea57c7
Create Date: 2020-11-19 17:52:22.155544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8395e165794'
down_revision = '5a6d53ea57c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attribute_map_id'), 'attribute_map', ['id'], unique=False)
    op.create_index(op.f('ix_bank_account_id'), 'bank_account', ['id'], unique=False)
    op.create_index(op.f('ix_blacklist_tokens_id'), 'blacklist_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_blockchain_address_id'), 'blockchain_address', ['id'], unique=False)
    op.create_index(op.f('ix_credit_transfer_id'), 'credit_transfer', ['id'], unique=False)
    op.create_index(op.f('ix_currency_conversion_id'), 'currency_conversion', ['id'], unique=False)
    op.create_index(op.f('ix_custom_attribute_id'), 'custom_attribute', ['id'], unique=False)
    op.create_index(op.f('ix_custom_attribute_user_storage_id'), 'custom_attribute_user_storage', ['id'], unique=False)
    op.create_index(op.f('ix_device_info_id'), 'device_info', ['id'], unique=False)
    op.create_index(op.f('ix_email_whitelist_id'), 'email_whitelist', ['id'], unique=False)
    op.create_index(op.f('ix_exchange_id'), 'exchange', ['id'], unique=False)
    op.create_index(op.f('ix_exchange_contract_id'), 'exchange_contract', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_fiat_ramp_id'), 'fiat_ramp', ['id'], unique=False)
    op.create_index(op.f('ix_ip_address_id'), 'ip_address', ['id'], unique=False)
    op.create_index(op.f('ix_kyc_application_id'), 'kyc_application', ['id'], unique=False)
    op.create_index(op.f('ix_organisation_id'), 'organisation', ['id'], unique=False)
    op.create_index(op.f('ix_saved_filter_id'), 'saved_filter', ['id'], unique=False)
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_spend_approval_id'), 'spend_approval', ['id'], unique=False)
    op.create_index(op.f('ix_token_id'), 'token', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_account_id'), 'transfer_account', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_card_id'), 'transfer_card', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_usage_id'), 'transfer_usage', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_resource_id'), 'uploaded_resource', ['id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_ussd_menu_id'), 'ussd_menu', ['id'], unique=False)
    op.create_index(op.f('ix_ussd_session_id'), 'ussd_session', ['id'], unique=False)
    op.create_index(op.f('ix_worker_messages_id'), 'worker_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_messages_id'), table_name='worker_messages')
    op.drop_index(op.f('ix_ussd_session_id'), table_name='ussd_session')
    op.drop_index(op.f('ix_ussd_menu_id'), table_name='ussd_menu')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_uploaded_resource_id'), table_name='uploaded_resource')
    op.drop_index(op.f('ix_transfer_usage_id'), table_name='transfer_usage')
    op.drop_index(op.f('ix_transfer_card_id'), table_name='transfer_card')
    op.drop_index(op.f('ix_transfer_account_id'), table_name='transfer_account')
    op.drop_index(op.f('ix_token_id'), table_name='token')
    op.drop_index(op.f('ix_spend_approval_id'), table_name='spend_approval')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_index(op.f('ix_saved_filter_id'), table_name='saved_filter')
    op.drop_index(op.f('ix_organisation_id'), table_name='organisation')
    op.drop_index(op.f('ix_kyc_application_id'), table_name='kyc_application')
    op.drop_index(op.f('ix_ip_address_id'), table_name='ip_address')
    op.drop_index(op.f('ix_fiat_ramp_id'), table_name='fiat_ramp')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_exchange_contract_id'), table_name='exchange_contract')
    op.drop_index(op.f('ix_exchange_id'), table_name='exchange')
    op.drop_index(op.f('ix_email_whitelist_id'), table_name='email_whitelist')
    op.drop_index(op.f('ix_device_info_id'), table_name='device_info')
    op.drop_index(op.f('ix_custom_attribute_user_storage_id'), table_name='custom_attribute_user_storage')
    op.drop_index(op.f('ix_custom_attribute_id'), table_name='custom_attribute')
    op.drop_index(op.f('ix_currency_conversion_id'), table_name='currency_conversion')
    op.drop_index(op.f('ix_credit_transfer_id'), table_name='credit_transfer')
    op.drop_index(op.f('ix_blockchain_address_id'), table_name='blockchain_address')
    op.drop_index(op.f('ix_blacklist_tokens_id'), table_name='blacklist_tokens')
    op.drop_index(op.f('ix_bank_account_id'), table_name='bank_account')
    op.drop_index(op.f('ix_attribute_map_id'), table_name='attribute_map')
    # ### end Alembic commands ###
