"""empty message

Revision ID: c9db3658816a
Revises: 2ccfaa8b79e7
Create Date: 2019-09-15 18:58:13.355607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9db3658816a'
down_revision = '2ccfaa8b79e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spend_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorising_user_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('eth_send_task_id', sa.Integer(), nullable=True),
    sa.Column('approval_task_id', sa.Integer(), nullable=True),
    sa.Column('receiving_address', sa.String(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('giving_transfer_account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['giving_transfer_account_id'], ['transfer_account.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('spend_approvals')
    op.add_column('organisation', sa.Column('system_blockchain_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'system_blockchain_address')
    op.create_table('spend_approvals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('authorising_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('eth_send_task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approval_task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('token_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('giving_transfer_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receiving_transfer_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['giving_transfer_account_id'], ['transfer_account.id'], name='spend_approvals_giving_transfer_account_id_fkey'),
    sa.ForeignKeyConstraint(['receiving_transfer_account_id'], ['transfer_account.id'], name='spend_approvals_receiving_transfer_account_id_fkey'),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], name='spend_approvals_token_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='spend_approvals_pkey')
    )
    op.drop_table('spend_approval')
    # ### end Alembic commands ###
