"""empty message

Revision ID: cdf09feaf0a5
Revises: fea16694457a
Create Date: 2019-10-21 17:29:35.948037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf09feaf0a5'
down_revision = 'fea16694457a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exchange_contract_transfer_account_id_fkey', 'exchange_contract', type_='foreignkey')
    op.drop_column('exchange_contract', 'transfer_account_id')
    op.add_column('transfer_account', sa.Column('exchange_contract_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer_account', 'exchange_contract', ['exchange_contract_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer_account', type_='foreignkey')
    op.drop_column('transfer_account', 'exchange_contract_id')
    op.add_column('exchange_contract', sa.Column('transfer_account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('exchange_contract_transfer_account_id_fkey', 'exchange_contract', 'transfer_account', ['transfer_account_id'], ['id'])
    # ### end Alembic commands ###
