"""empty message

Revision ID: ce41ff512059
Revises: 0017795ec52e
Create Date: 2020-01-03 13:49:58.224542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce41ff512059'
down_revision = '0017795ec52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('blockchain_task_uuid', sa.String(), nullable=True))
    op.drop_column('credit_transfer', 'blockchain_task_id')
    op.add_column('exchange', sa.Column('blockchain_task_uuid', sa.String(), nullable=True))
    op.drop_column('exchange', 'blockchain_task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange', sa.Column('blockchain_task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('exchange', 'blockchain_task_uuid')
    op.add_column('credit_transfer', sa.Column('blockchain_task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('credit_transfer', 'blockchain_task_uuid')
    # ### end Alembic commands ###
