"""Add user ID to token blacklist

Revision ID: ceec78f714fc
Revises: dd768e99637e
Create Date: 2022-03-14 17:06:16.327551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceec78f714fc'
down_revision = 'dd768e99637e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist_tokens', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_blacklist_tokens_user_id'), 'blacklist_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklist_tokens_user_id'), table_name='blacklist_tokens')
    op.drop_column('blacklist_tokens', 'user_id')
    # ### end Alembic commands ###
