"""empty message

Revision ID: d0088b4df549
Revises: b40055ad9587
Create Date: 2019-10-30 22:15:22.015323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0088b4df549'
down_revision = 'b40055ad9587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_encrypted_pin', sa.String(), nullable=True))
    op.add_column('user', sa.Column('failed_pin_attempts', sa.Integer(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'failed_pin_attempts')
    op.drop_column('user', '_encrypted_pin')
    # ### end Alembic commands ###
