"""empty message

Revision ID: d0f42c2a8483
Revises: 40557cd73140
Create Date: 2020-04-23 17:17:00.182725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f42c2a8483'
down_revision = '40557cd73140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_messages', sa.Column('worker_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_messages', 'worker_timestamp')
    # ### end Alembic commands ###
