"""empty message

Revision ID: d1e9ab6c872c
Revises: 2460fe231511
Create Date: 2019-11-08 11:22:16.506099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e9ab6c872c'
down_revision = '2460fe231511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('_transfer_amount_wei', sa.Numeric(precision=27), nullable=True))
    op.drop_column('credit_transfer', '_transfer_amount')
    op.add_column('transfer_account', sa.Column('_balance_wei', sa.Numeric(precision=27), nullable=True))
    op.drop_column('transfer_account', '_balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('_balance', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('transfer_account', '_balance_wei')
    op.add_column('credit_transfer', sa.Column('_transfer_amount', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('credit_transfer', '_transfer_amount_wei')
    # ### end Alembic commands ###
