"""Attach disbursement to organisation

Revision ID: d2591d44b5c4
Revises: dc6a78f80117
Create Date: 2021-06-22 15:47:57.467723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2591d44b5c4'
down_revision = 'dc6a78f80117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disbursement', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('disbursement', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'disbursement', 'organisation', ['organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disbursement', type_='foreignkey')
    op.drop_column('disbursement', 'organisation_id')
    op.drop_column('disbursement', 'is_public')
    # ### end Alembic commands ###
