"""empty message

Revision ID: d3bff62150fa
Revises: fbd0f6a88346
Create Date: 2020-09-09 14:40:15.418550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3bff62150fa'
down_revision = 'fbd0f6a88346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('received_third_party_sync', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_transfer', 'received_third_party_sync')
    # ### end Alembic commands ###
