"""empty message

Revision ID: d4b0c04961cc
Revises: 984d7e9c50af
Create Date: 2020-05-05 12:08:36.455981

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd4b0c04961cc'
down_revision = '984d7e9c50af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")

    op.execute("ALTER TYPE transfermodeenum ADD VALUE 'USSD'")
    op.execute("ALTER TYPE transfermodeenum ADD VALUE 'WEB'")
    op.execute("ALTER TYPE transfermodeenum ADD VALUE 'EXTERNAL'")
    op.execute("ALTER TYPE transfermodeenum ADD VALUE 'MOBILE'")
    op.execute(
        "UPDATE credit_transfer SET transfer_mode = 'WEB' WHERE transfer_subtype = 'DISBURSEMENT' OR transfer_subtype = 'RECLAMATION'")
    op.execute("UPDATE credit_transfer SET transfer_mode = 'USSD' WHERE transfer_mode is NULL")
    # ### end Alembic commands ###


def downgrade():
    pass
#     POSTGRES DOESN'T SUPPORT REMOVING OF ENUMS
#     " Existing values cannot be removed from an enum type, nor can the sort ordering of such values be changed,
#      short of dropping and re-creating the enum type."
