"""empty message

Revision ID: d54db8c7fa27
Revises: cdf09feaf0a5
Create Date: 2019-10-21 18:22:00.660542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54db8c7fa27'
down_revision = 'cdf09feaf0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_public')
    op.drop_column('credit_transfer', 'is_public')
    # ### end Alembic commands ###
