"""empty message

Revision ID: d5ac8e623850
Revises: 3c3e57766bff
Create Date: 2019-08-26 20:21:13.033702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ac8e623850'
down_revision = '3c3e57766bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('token_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'credit_transfer', 'token', ['token_id'], ['id'])
    op.add_column('transfer_account', sa.Column('token_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer_account', 'token', ['token_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer_account', type_='foreignkey')
    op.drop_column('transfer_account', 'token_id')
    op.drop_constraint(None, 'credit_transfer', type_='foreignkey')
    op.drop_column('credit_transfer', 'token_id')
    # ### end Alembic commands ###
