"""empty message

Revision ID: d7d94595a720
Revises: e20ce46bcc2f
Create Date: 2018-10-18 10:04:20.912279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d94595a720'
down_revision = 'e20ce46bcc2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_disabled', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_deactivated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deactivated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'is_disabled')
    # ### end Alembic commands ###
