"""empty message

Revision ID: d8c2cea7f70b
Revises: 74c172d7b711
Create Date: 2019-09-13 16:39:32.520542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c2cea7f70b'
down_revision = '74c172d7b711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_beneficiary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_beneficiary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
