"""Add approval times

Revision ID: dc6a78f80117
Revises: b99d4ea009a2
Create Date: 2021-05-05 14:16:48.765048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6a78f80117'
down_revision = 'b99d4ea009a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disbursement', sa.Column('approval_times', sa.ARRAY(sa.DateTime()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disbursement', 'approval_times')
    # ### end Alembic commands ###
