"""empty message

Revision ID: dcaf48442917
Revises: f5383ac03cf1
Create Date: 2019-06-17 11:18:09.910479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcaf48442917'
down_revision = 'f5383ac03cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('TFA_secret', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'TFA_secret')
    # ### end Alembic commands ###
