"""empty message

Revision ID: dd768e99637e
Revises: bc84f5f02e9c
Create Date: 2022-01-06 16:23:39.800638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd768e99637e'
down_revision = 'bc84f5f02e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attribute_map_is_public'), 'attribute_map', ['is_public'], unique=False)
    op.create_index(op.f('ix_blockchain_address_is_public'), 'blockchain_address', ['is_public'], unique=False)
    op.create_index(op.f('ix_credit_transfer_is_public'), 'credit_transfer', ['is_public'], unique=False)
    op.create_index(op.f('ix_disbursement_is_public'), 'disbursement', ['is_public'], unique=False)
    op.create_index(op.f('ix_email_whitelist_is_public'), 'email_whitelist', ['is_public'], unique=False)
    op.create_index(op.f('ix_exchange_from_transfer_id'), 'exchange', ['from_transfer_id'], unique=False)
    op.create_index(op.f('ix_exchange_to_transfer_id'), 'exchange', ['to_transfer_id'], unique=False)
    op.create_index(op.f('ix_saved_filter_is_public'), 'saved_filter', ['is_public'], unique=False)
    op.create_index(op.f('ix_settings_is_public'), 'settings', ['is_public'], unique=False)
    op.create_index(op.f('ix_transfer_account_is_public'), 'transfer_account', ['is_public'], unique=False)
    op.create_index(op.f('ix_uploaded_resource_credit_transfer_id'), 'uploaded_resource', ['credit_transfer_id'], unique=False)
    op.create_index(op.f('ix_user_is_public'), 'user', ['is_public'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_public'), table_name='user')
    op.drop_index(op.f('ix_uploaded_resource_credit_transfer_id'), table_name='uploaded_resource')
    op.drop_index(op.f('ix_transfer_account_is_public'), table_name='transfer_account')
    op.drop_index(op.f('ix_settings_is_public'), table_name='settings')
    op.drop_index(op.f('ix_saved_filter_is_public'), table_name='saved_filter')
    op.drop_index(op.f('ix_exchange_to_transfer_id'), table_name='exchange')
    op.drop_index(op.f('ix_exchange_from_transfer_id'), table_name='exchange')
    op.drop_index(op.f('ix_email_whitelist_is_public'), table_name='email_whitelist')
    op.drop_index(op.f('ix_disbursement_is_public'), table_name='disbursement')
    op.drop_index(op.f('ix_credit_transfer_is_public'), table_name='credit_transfer')
    op.drop_index(op.f('ix_blockchain_address_is_public'), table_name='blockchain_address')
    op.drop_index(op.f('ix_attribute_map_is_public'), table_name='attribute_map')
    # ### end Alembic commands ###
