"""empty message

Revision ID: dfd50c445eb7
Revises: dbbbe8888006
Create Date: 2018-12-01 14:20:05.961933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd50c445eb7'
down_revision = 'dbbbe8888006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency_conversion', 'usd_equiv')
    op.add_column('user', sa.Column('default_currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'default_currency')
    op.add_column('currency_conversion', sa.Column('usd_equiv', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
