"""empty message

Revision ID: e20ce46bcc2f
Revises: 05972cb08ae6
Create Date: 2018-10-17 15:36:24.500084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20ce46bcc2f'
down_revision = '05972cb08ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_whitelist', sa.Column('tier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_whitelist', 'tier')
    # ### end Alembic commands ###
