"""empty message

Revision ID: e2a69c899f32
Revises: 7de5d1973128
Create Date: 2019-04-28 00:42:18.709150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2a69c899f32'
down_revision = '7de5d1973128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('transfer_use', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credit_transfer', 'transfer_use')
    # ### end Alembic commands ###
