"""empty message

Revision ID: e2b09de8e721
Revises: 6dd1e66336af
Create Date: 2018-10-01 16:39:04.116216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b09de8e721'
down_revision = '6dd1e66336af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deactivated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deactivated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
