"""empty message

Revision ID: e369fe1c0bb1
Revises: d54db8c7fa27
Create Date: 2019-10-21 18:35:28.690720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e369fe1c0bb1'
down_revision = 'd54db8c7fa27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_address', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('email_whitelist', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('transfer_account', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_account', 'is_public')
    op.drop_column('email_whitelist', 'is_public')
    op.drop_column('blockchain_address', 'is_public')
    # ### end Alembic commands ###
