"""empty message

Revision ID: e44eb2604c0c
Revises: 583b272376f7
Create Date: 2019-11-02 11:09:05.261313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44eb2604c0c'
down_revision = '583b272376f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_credit_transfer_sender_user_id'), 'credit_transfer', ['sender_user_id'], unique=False)
    op.create_index('updated_index', 'credit_transfer', ['updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('updated_index', table_name='credit_transfer')
    op.drop_index(op.f('ix_credit_transfer_sender_user_id'), table_name='credit_transfer')
    # ### end Alembic commands ###
