"""empty message

Revision ID: e45e3a3b9316
Revises: e2b09de8e721
Create Date: 2018-10-01 16:39:36.259151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45e3a3b9316'
down_revision = 'e2b09de8e721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deactivated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_deactivated')
    # ### end Alembic commands ###
