"""empty message

Revision ID: e6a3faa40a4c
Revises: c773e3513ff1
Create Date: 2019-11-02 15:21:02.112961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6a3faa40a4c'
down_revision = 'c773e3513ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pin_reset_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('user', 'failed_pin_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'failed_pin_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user', 'pin_reset_tokens')
    # ### end Alembic commands ###
