"""empty message

Revision ID: eb55e0465a4a
Revises: 311569eda055
Create Date: 2019-09-08 22:59:15.030792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb55e0465a4a'
down_revision = '311569eda055'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('organisation', sa.Column('token_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'organisation', 'token', ['token_id'], ['id'])
    # op.drop_column('user', 'is_beneficiary')
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('is_beneficiary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # op.drop_constraint(None, 'organisation', type_='foreignkey')
    # op.drop_column('organisation', 'token_id')
    # ### end Alembic commands ###
