"""empty message

Revision ID: eb7ea57ebad0
Revises: 558c9667af5f
Create Date: 2018-09-03 16:55:24.616269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7ea57ebad0'
down_revision = '558c9667af5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_account', 'secret')
    # ### end Alembic commands ###
