"""empty message

Revision ID: ed919f758803
Revises: 49e8a333d285
Create Date: 2020-07-16 12:58:19.829623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed919f758803'
down_revision = '49e8a333d285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE transferaccounttype ADD VALUE 'EXTERNAL'")
    # ### end Alembic commands ###


def downgrade():
    pass
#     POSTGRES DOESN'T SUPPORT REMOVING OF ENUMS
#     " Existing values cannot be removed from an enum type, nor can the sort ordering of such values be changed,
#      short of dropping and re-creating the enum type."