"""empty message

Revision ID: eeb1fe1a4999
Revises: ba9c2a8e7338
Create Date: 2020-01-17 12:36:58.894150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb1fe1a4999'
down_revision = 'ba9c2a8e7338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('referrer_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('referred_user_id', 'referrer_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referrals')
    # ### end Alembic commands ###
