"""Add mint enum

Revision ID: efb8537855a8
Revises: 50fa8260cee7
Create Date: 2022-09-15 14:21:37.580109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb8537855a8'
down_revision = '50fa8260cee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE transfertypeenum ADD VALUE 'MINT'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return
    # ### end Alembic commands ###
