"""Add index for subtype and transfer usages

Revision ID: f048bd12da6a
Revises: 1a762e73a3be
Create Date: 2021-09-08 13:23:18.476659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f048bd12da6a'
down_revision = '1a762e73a3be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_credit_transfer_transfer_subtype'), 'credit_transfer', ['transfer_subtype'], unique=False)
    op.create_index(op.f('ix_custom_attribute_filter_visibility'), 'custom_attribute', ['filter_visibility'], unique=False)
    op.create_index(op.f('ix_custom_attribute_group_visibility'), 'custom_attribute', ['group_visibility'], unique=False)
    op.create_index(op.f('ix_transfer_usage__name'), 'transfer_usage', ['_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_usage__name'), table_name='transfer_usage')
    op.drop_index(op.f('ix_custom_attribute_group_visibility'), table_name='custom_attribute')
    op.drop_index(op.f('ix_custom_attribute_filter_visibility'), table_name='custom_attribute')
    op.drop_index(op.f('ix_credit_transfer_transfer_subtype'), table_name='credit_transfer')
    # ### end Alembic commands ###
