"""empty message

Revision ID: f2d2fff32732
Revises: b167606c5081
Create Date: 2018-10-23 14:13:36.225944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d2fff32732'
down_revision = 'b167606c5081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist_tokens', sa.Column('authorising_user_id', sa.Integer(), nullable=True))
    op.add_column('blacklist_tokens', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('blacklist_tokens', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('blockchain_address', sa.Column('authorising_user_id', sa.Integer(), nullable=True))
    op.add_column('blockchain_address', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('blockchain_transaction', sa.Column('authorising_user_id', sa.Integer(), nullable=True))
    op.add_column('blockchain_transaction', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('chatbot_state', sa.Column('authorising_user_id', sa.Integer(), nullable=True))
    op.add_column('chatbot_state', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('credit_transfer', sa.Column('authorising_user_id', sa.Integer(), nullable=True))
    op.add_column('credit_transfer', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('custom_settings', sa.Column('authorising_user_id', sa.Integer(), nullable=True))
    op.add_column('custom_settings', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('device_info', sa.Column('authorising_user_id', sa.Integer(), nullable=True))
    op.add_column('device_info', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('email_whitelist', sa.Column('authorising_user_id', sa.Integer(), nullable=True))
    op.add_column('email_whitelist', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('feedback', sa.Column('authorising_user_id', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('public_serial_number', sa.Column('authorising_user_id', sa.Integer(), nullable=True))
    op.add_column('public_serial_number', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('public_serial_number', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('targeting_survey', sa.Column('authorising_user_id', sa.Integer(), nullable=True))
    op.add_column('targeting_survey', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('transfer_account', sa.Column('authorising_user_id', sa.Integer(), nullable=True))
    op.add_column('transfer_account', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('authorising_user_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated')
    op.drop_column('user', 'authorising_user_id')
    op.drop_column('transfer_account', 'updated')
    op.drop_column('transfer_account', 'authorising_user_id')
    op.drop_column('targeting_survey', 'updated')
    op.drop_column('targeting_survey', 'authorising_user_id')
    op.drop_column('public_serial_number', 'updated')
    op.drop_column('public_serial_number', 'created')
    op.drop_column('public_serial_number', 'authorising_user_id')
    op.drop_column('feedback', 'updated')
    op.drop_column('feedback', 'authorising_user_id')
    op.drop_column('email_whitelist', 'updated')
    op.drop_column('email_whitelist', 'authorising_user_id')
    op.drop_column('device_info', 'updated')
    op.drop_column('device_info', 'authorising_user_id')
    op.drop_column('custom_settings', 'updated')
    op.drop_column('custom_settings', 'authorising_user_id')
    op.drop_column('credit_transfer', 'updated')
    op.drop_column('credit_transfer', 'authorising_user_id')
    op.drop_column('chatbot_state', 'updated')
    op.drop_column('chatbot_state', 'authorising_user_id')
    op.drop_column('blockchain_transaction', 'updated')
    op.drop_column('blockchain_transaction', 'authorising_user_id')
    op.drop_column('blockchain_address', 'updated')
    op.drop_column('blockchain_address', 'authorising_user_id')
    op.drop_column('blacklist_tokens', 'updated')
    op.drop_column('blacklist_tokens', 'created')
    op.drop_column('blacklist_tokens', 'authorising_user_id')
    # ### end Alembic commands ###
