"""empty message

Revision ID: f2e8611809f4
Revises: b8f99367e8fa
Create Date: 2019-06-19 14:55:07.095557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e8611809f4'
down_revision = 'b8f99367e8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('TFA_enabled', sa.Boolean(), nullable=True))
    op.drop_column('user', '_TFA_enabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_TFA_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'TFA_enabled')
    # ### end Alembic commands ###
