"""Add valid_roles

Revision ID: f3d211a77ca1
Revises: ab9c0ee81345
Create Date: 2020-08-20 13:10:30.110387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3d211a77ca1'
down_revision = 'ab9c0ee81345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation', sa.Column('valid_roles', postgresql.ARRAY(sa.String(), dimensions=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'valid_roles')
    # ### end Alembic commands ###
