"""empty message

Revision ID: f5383ac03cf1
Revises: 2cbb3f38576a
Create Date: 2019-05-02 19:19:53.928913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5383ac03cf1'
down_revision = '2cbb3f38576a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cashout_authorised', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cashout_authorised')
    # ### end Alembic commands ###
