"""empty message

Revision ID: f695fffd9dca
Revises: d8c2cea7f70b
Create Date: 2019-09-13 17:12:59.945454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f695fffd9dca'
down_revision = 'd8c2cea7f70b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('owning_organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer_account', 'organisation', ['owning_organisation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer_account', type_='foreignkey')
    op.drop_column('transfer_account', 'owning_organisation_id')
    # ### end Alembic commands ###
