"""empty message

Revision ID: f877c9a46ab1
Revises: 603694d49e24
Create Date: 2019-08-22 14:39:07.104599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f877c9a46ab1'
down_revision = '603694d49e24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_whitelist', sa.Column('referral_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_whitelist', 'referral_code')
    # ### end Alembic commands ###
