"""empty message

Revision ID: f8d4b8b18da8
Revises: 3d146d7e19c4
Create Date: 2018-10-18 10:30:52.453196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d4b8b18da8'
down_revision = '3d146d7e19c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_account', sa.Column('payable_epoch', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_account', 'payable_epoch')
    # ### end Alembic commands ###
