"""empty message

Revision ID: fbba33e6bd4b
Revises: 52bda03997d7
Create Date: 2019-10-23 11:21:14.940444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbba33e6bd4b'
down_revision = '52bda03997d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('primary_blockchain_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'primary_blockchain_address')
    # ### end Alembic commands ###
