"""empty message

Revision ID: fbd0f6a88346
Revises: 230b0adb87af
Create Date: 2020-07-24 23:48:44.360452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fbd0f6a88346'
down_revision = '230b0adb87af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transfer_transfer_usage_association_table',
    sa.Column('credit_transfer_id', sa.Integer(), nullable=True),
    sa.Column('transfer_usage_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_transfer_id'], ['credit_transfer.id'], ),
    sa.ForeignKeyConstraint(['transfer_usage_id'], ['transfer_usage.id'], )
    )
    op.create_index(op.f('ix_credit_transfer_transfer_usage_association_table_credit_transfer_id'), 'credit_transfer_transfer_usage_association_table', ['credit_transfer_id'], unique=False)
    op.create_index(op.f('ix_credit_transfer_transfer_usage_association_table_transfer_usage_id'), 'credit_transfer_transfer_usage_association_table', ['transfer_usage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_transfer_transfer_usage_association_table_transfer_usage_id'), table_name='credit_transfer_transfer_usage_association_table')
    op.drop_index(op.f('ix_credit_transfer_transfer_usage_association_table_credit_transfer_id'), table_name='credit_transfer_transfer_usage_association_table')
    op.drop_table('credit_transfer_transfer_usage_association_table')
    # ### end Alembic commands ###
