"""empty message

Revision ID: fc2eeba8e8e8
Revises: ae7809eb2557
Create Date: 2020-02-06 18:17:11.218770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2eeba8e8e8'
down_revision = 'ae7809eb2557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('exclude_from_limit_calcs', sa.Boolean(), nullable=True))
    op.add_column('kyc_application', sa.Column('multiple_documents_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc_application', 'multiple_documents_verified')
    op.drop_column('credit_transfer', 'exclude_from_limit_calcs')
    # ### end Alembic commands ###
