"""empty message

Revision ID: fe36052e1fa5
Revises: c392929a91cc
Create Date: 2019-07-28 22:00:40.734256

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe36052e1fa5'
down_revision = 'c392929a91cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_application', sa.Column('kyc_actions', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('kyc_application', sa.Column('trulioo_id', sa.String(), nullable=True))
    op.add_column('kyc_application', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'kyc_application', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kyc_application', type_='foreignkey')
    op.drop_column('kyc_application', 'user_id')
    op.drop_column('kyc_application', 'trulioo_id')
    op.drop_column('kyc_application', 'kyc_actions')
    # ### end Alembic commands ###
