"""empty message

Revision ID: fee617363e27
Revises: 091221bd6d58
Create Date: 2019-05-01 15:40:42.607909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee617363e27'
down_revision = '091221bd6d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('old_uuid', sa.String(), nullable=True))
    op.drop_column('credit_transfer', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credit_transfer', sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('credit_transfer', 'old_uuid')
    # ### end Alembic commands ###
