"""empty message

Revision ID: ff11abbef524
Revises: b13e56673261
Create Date: 2019-03-03 14:25:17.130369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff11abbef524'
down_revision = 'b13e56673261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('btc_spend_txn', sa.String(), nullable=True))
    op.add_column('blockchain_transaction', sa.Column('is_bitcoin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_transaction', 'is_bitcoin')
    op.drop_column('blockchain_transaction', 'btc_spend_txn')
    # ### end Alembic commands ###
