creation_rules:
  - path_regex: .*/config_files/.*|.*/.sempoconfig/.*
    key_groups:
    - pgp:
      - 0C27750BA15B3AE283591F3FE94556EE82B0CB55
      kms:
      - arn: arn:aws:kms:ap-southeast-2:290492953667:key/76efe185-c961-49cb-be7a-8b140fc0c924
        aws_profile: sempo
