codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
    after_n_builds: 3

coverage:
  status:
    project:
      default: false
      patch:
        threshold: 2
      server:
        paths:
          - "app/server"
      client:
        paths:
          - "app/client"
          - "!app/client/__fixtures__"
          - "!app/client/__mocks__"
          - "!app/client/__tests__"
      eth_worker:
        paths:
          - "eth_worker/src"
      #tests:
      #paths:
      #- "app/test_app"
      #- "app/client/__tests__"
      #- "eth_worker/test_eth_worker"
      #threshold: 100%
fixes:
  #  Server Fixes
  - "server/::app/server/"
  - "test_app/::app/test_app/"
  - "manage.py::app/manage.py"
  - "migrations/seed.py::app/migrations/seed.py"
  # Client Fixes
  - "client/::app/client/"
  #Eth Worker Fixes
  - "eth_src/::eth_worker/eth_src/" #We use eth_src instead of just src to prevent potential collisions with other src directories
  - "test_eth_worker/::eth_worker/test_eth_worker/"
  #Commons Fixes
  - "generate_secrets.py::config_files/generate_secrets.py"
