// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  code: string;
  error: string;
  input: string;
  inputBlock: string;
  inputLabel: string;
  required: string;
  select: string;
}
export const cssExports: CssExports;
export default cssExports;
