// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'code': string;
  'error': string;
  'input': string;
  'inputBlock': string;
  'inputLabel': string;
  'required': string;
}
declare const cssExports: CssExports;
export = cssExports;
