# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  ganache-cli = nodeEnv.buildNodePackage {
    name = "ganache-cli";
    packageName = "ganache-cli";
    version = "6.9.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/ganache-cli/-/ganache-cli-6.9.1.tgz";
      sha512 = "VPBumkNUZzXDRQwVOby5YyQpd5t1clkr06xMgB28lZdEIn5ht1GMwUskOTFOAxdkQ4J12IWP0gdeacVRGowqbA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "<p align=\"center\">   <em>NOTICE</em>: <code>testrpc</code> is now <code>ganache-cli</code>. Use it just as you would <code>testrpc</code>. </p> <hr/>";
      homepage = "https://github.com/trufflesuite/ganache-cli#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}