"""empty message

Revision ID: 02af049dc9fe
Revises: 47c69b4373f2
Create Date: 2019-10-26 14:36:10.239861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02af049dc9fe'
down_revision = '47c69b4373f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('contract_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_transaction', 'contract_address')
    # ### end Alembic commands ###
