"""empty message

Revision ID: 07041f16c41b
Revises: 
Create Date: 2019-09-07 23:01:34.629043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07041f16c41b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('_encrypted_private_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blockchain_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('contract', sa.String(), nullable=True),
    sa.Column('function', sa.String(), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('kwargs', sa.JSON(), nullable=True),
    sa.Column('signing_address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['signing_address_id'], ['blockchain_address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blockchain_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('_status', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('mined_date', sa.DateTime(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=True),
    sa.Column('nonce_consumed', sa.Boolean(), nullable=True),
    sa.Column('signing_address_id', sa.Integer(), nullable=True),
    sa.Column('blockchain_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blockchain_task_id'], ['blockchain_task.id'], ),
    sa.ForeignKeyConstraint(['signing_address_id'], ['blockchain_address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blockchain_transaction')
    op.drop_table('blockchain_task')
    op.drop_table('blockchain_address')
    # ### end Alembic commands ###
