"""empty message

Revision ID: 0b4247c52ad5
Revises: e932b738ea4a
Create Date: 2019-12-03 12:54:44.754539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4247c52ad5'
down_revision = 'e932b738ea4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('first_block_hash', sa.String(), nullable=True))
    op.drop_column('blockchain_transaction', 'coinbase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('coinbase', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blockchain_transaction', 'first_block_hash')
    # ### end Alembic commands ###
