"""empty message

Revision ID: 1dc62b5f4746
Revises: 
Create Date: 2019-09-05 07:22:34.655839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc62b5f4746'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('signing_address', sa.String(), nullable=True),
    sa.Column('contract', sa.String(), nullable=True),
    sa.Column('function', sa.String(), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('kwargs', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blockchain_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('signing_address', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('mined_date', sa.DateTime(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=True),
    sa.Column('blockchain_task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blockchain_task_id'], ['blockchain_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blockchain_transaction')
    op.drop_table('blockchain_task')
    # ### end Alembic commands ###
