"""empty message

Revision ID: 334ff08dacf9
Revises: 3bacad411309
Create Date: 2019-09-29 17:48:17.263827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334ff08dacf9'
down_revision = '3bacad411309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_wallet', sa.Column('last_topup_task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_blockchain_wallet_address'), 'blockchain_wallet', ['address'], unique=True)
    op.drop_index('ix_blockchain_address_address', table_name='blockchain_wallet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_blockchain_address_address', 'blockchain_wallet', ['address'], unique=True)
    op.drop_index(op.f('ix_blockchain_wallet_address'), table_name='blockchain_wallet')
    op.drop_column('blockchain_wallet', 'last_topup_task_id')
    # ### end Alembic commands ###
