"""empty message

Revision ID: 351f7989ba55
Revises: 4f7fcf6a4a7f
Create Date: 2020-06-11 19:46:23.561148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351f7989ba55'
down_revision = '4f7fcf6a4a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('is_third_party_transaction', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_transaction', 'is_third_party_transaction')
    # ### end Alembic commands ###
