"""empty message

Revision ID: 375a2ed92c81
Revises: 1dc62b5f4746
Create Date: 2019-09-05 17:32:22.582193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375a2ed92c81'
down_revision = '1dc62b5f4746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('_status', sa.String(), nullable=True))
    op.drop_column('blockchain_transaction', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blockchain_transaction', '_status')
    # ### end Alembic commands ###
