"""empty message

Revision ID: 47c69b4373f2
Revises: afb30cf52529
Create Date: 2019-10-26 14:16:36.794784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c69b4373f2'
down_revision = 'afb30cf52529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('coinbase', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_transaction', 'coinbase')
    # ### end Alembic commands ###
