"""empty message

Revision ID: 493f16271f80
Revises: 63a93a8de3dc
Create Date: 2019-11-03 17:44:18.197636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493f16271f80'
down_revision = '63a93a8de3dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('coinbase', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_transaction', 'coinbase')
    # ### end Alembic commands ###
