"""Adds sender/recipient/amount so we have all the data we need to sync third party transactions

Revision ID: 4e492f7dba64
Revises: d087cd128e00
Create Date: 2020-06-08 12:52:58.262456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e492f7dba64'
down_revision = 'd087cd128e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('amount', sa.Numeric(precision=27), nullable=True))
    op.add_column('blockchain_transaction', sa.Column('recipient_address', sa.String(), nullable=True))
    op.add_column('blockchain_transaction', sa.Column('sender_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_transaction', 'sender_address')
    op.drop_column('blockchain_transaction', 'recipient_address')
    op.drop_column('blockchain_transaction', 'amount')
    # ### end Alembic commands ###
