"""empty message

Revision ID: 4f7fcf6a4a7f
Revises: a346b9390fe3
Create Date: 2020-06-11 15:36:29.134374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f7fcf6a4a7f'
down_revision = 'a346b9390fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synchronization_filter', sa.Column('max_block', sa.Integer(), nullable=True))
    op.drop_column('synchronization_filter', 'last_block_synchronized')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synchronization_filter', sa.Column('last_block_synchronized', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('synchronization_filter', 'max_block')
    # ### end Alembic commands ###
