"""empty message

Revision ID: 50df11816a5d
Revises: 375a2ed92c81
Create Date: 2019-09-05 17:59:56.763609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50df11816a5d'
down_revision = '375a2ed92c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_transaction', 'error')
    # ### end Alembic commands ###
