"""empty message

Revision ID: 5d327a0b562f
Revises: 9e96b52b50d8
Create Date: 2019-09-16 10:24:42.116413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d327a0b562f'
down_revision = '9e96b52b50d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_task', sa.Column('gas_limit', sa.BigInteger(), nullable=True))
    op.drop_column('blockchain_task', 'gasLimit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_task', sa.Column('gasLimit', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('blockchain_task', 'gas_limit')
    # ### end Alembic commands ###
