"""
Adds index to commonly queried blockchain_task_id col

Revision ID: 5e0df61f29cc
Revises: c81dbf171b47
Create Date: 2020-11-12 15:20:19.429016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0df61f29cc'
down_revision = 'c81dbf171b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blockchain_transaction_blockchain_task_id'), 'blockchain_transaction', ['blockchain_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blockchain_transaction_blockchain_task_id'), table_name='blockchain_transaction')
    # ### end Alembic commands ###
