"""empty message

Revision ID: 606591437586
Revises: 5d327a0b562f
Create Date: 2019-09-29 16:41:56.461183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606591437586'
down_revision = '5d327a0b562f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_address', sa.Column('wei_topup_amount', sa.BigInteger(), nullable=True))
    op.add_column('blockchain_address', sa.Column('wei_topup_threshold', sa.BigInteger(), nullable=True))
    op.add_column('blockchain_task', sa.Column('signing_wallet_id', sa.Integer(), nullable=True))
    op.drop_constraint('blockchain_task_signing_address_id_fkey', 'blockchain_task', type_='foreignkey')
    op.create_foreign_key(None, 'blockchain_task', 'blockchain_address', ['signing_wallet_id'], ['id'])
    op.drop_column('blockchain_task', 'signing_address_id')
    op.add_column('blockchain_transaction', sa.Column('signing_wallet_id', sa.Integer(), nullable=True))
    op.drop_constraint('blockchain_transaction_signing_address_id_fkey', 'blockchain_transaction', type_='foreignkey')
    op.create_foreign_key(None, 'blockchain_transaction', 'blockchain_address', ['signing_wallet_id'], ['id'])
    op.drop_column('blockchain_transaction', 'signing_address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('signing_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blockchain_transaction', type_='foreignkey')
    op.create_foreign_key('blockchain_transaction_signing_address_id_fkey', 'blockchain_transaction', 'blockchain_address', ['signing_address_id'], ['id'])
    op.drop_column('blockchain_transaction', 'signing_wallet_id')
    op.add_column('blockchain_task', sa.Column('signing_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blockchain_task', type_='foreignkey')
    op.create_foreign_key('blockchain_task_signing_address_id_fkey', 'blockchain_task', 'blockchain_address', ['signing_address_id'], ['id'])
    op.drop_column('blockchain_task', 'signing_wallet_id')
    op.drop_column('blockchain_address', 'wei_topup_threshold')
    op.drop_column('blockchain_address', 'wei_topup_amount')
    # ### end Alembic commands ###
