"""empty message

Revision ID: 668cccfdad09
Revises: 07041f16c41b
Create Date: 2019-09-08 19:02:11.869710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668cccfdad09'
down_revision = '07041f16c41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('dependent_task_id', sa.Integer(), nullable=False),
    sa.Column('dependee_task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dependee_task_id'], ['blockchain_task.id'], ),
    sa.ForeignKeyConstraint(['dependent_task_id'], ['blockchain_task.id'], ),
    sa.PrimaryKeyConstraint('dependent_task_id', 'dependee_task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dependencies')
    # ### end Alembic commands ###
