"""empty message

Revision ID: 6ab94e3c23df
Revises: e932b738ea4a
Create Date: 2019-12-02 16:06:33.127596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab94e3c23df'
down_revision = 'e932b738ea4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('first_hash', sa.String(), nullable=True))
    op.drop_column('blockchain_transaction', 'coinbase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('coinbase', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blockchain_transaction', 'first_hash')
    # ### end Alembic commands ###
