"""empty message

Revision ID: 937abec76ce8
Revises: bcabc2834c03
Create Date: 2020-01-03 18:24:45.523100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937abec76ce8'
down_revision = 'bcabc2834c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_wallet', sa.Column('last_topup_task_uuid', sa.String(), nullable=True))
    op.drop_column('blockchain_wallet', 'last_topup_task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_wallet', sa.Column('last_topup_task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('blockchain_wallet', 'last_topup_task_uuid')
    # ### end Alembic commands ###
