"""empty message

Revision ID: a346b9390fe3
Revises: f931e179d451
Create Date: 2020-06-11 12:59:03.981105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a346b9390fe3'
down_revision = 'f931e179d451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
