"""empty message

Revision ID: a5eac7e0ab4b
Revises: b105c23bcd05
Create Date: 2020-03-12 09:35:14.967209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5eac7e0ab4b'
down_revision = 'b105c23bcd05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_task', sa.Column('reverses_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blockchain_task', 'blockchain_task', ['reverses_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blockchain_task', type_='foreignkey')
    op.drop_column('blockchain_task', 'reverses_id')
    # ### end Alembic commands ###
