"""empty message

Revision ID: aed2d49731a5
Revises: a3ab66ee419b
Create Date: 2020-11-17 10:18:10.795543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aed2d49731a5'
down_revision = 'a3ab66ee419b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_synchronized_block_block_number'), 'synchronized_block', ['block_number'], unique=False)
    op.create_index(op.f('ix_synchronized_block_synchronization_filter_id'), 'synchronized_block', ['synchronization_filter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_synchronized_block_synchronization_filter_id'), table_name='synchronized_block')
    op.drop_index(op.f('ix_synchronized_block_block_number'), table_name='synchronized_block')
    # ### end Alembic commands ###
