"""empty message

Revision ID: afb30cf52529
Revises: 1c60a911a555
Create Date: 2019-10-25 11:23:33.149890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb30cf52529'
down_revision = '1c60a911a555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_task', sa.Column('_type', sa.String(), nullable=True))
    op.add_column('blockchain_task', sa.Column('contract_address', sa.String(), nullable=True))
    op.add_column('blockchain_task', sa.Column('contract_name', sa.String(), nullable=True))
    op.drop_column('blockchain_task', 'contract')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_task', sa.Column('contract', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blockchain_task', 'contract_name')
    op.drop_column('blockchain_task', 'contract_address')
    op.drop_column('blockchain_task', '_type')
    # ### end Alembic commands ###
