"""empty message

Revision ID: b105c23bcd05
Revises: fae8445ececd
Create Date: 2020-01-11 12:17:03.802009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b105c23bcd05'
down_revision = 'fae8445ececd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_dependencies', sa.Column('posterior_task_id', sa.Integer(), nullable=False))
    op.add_column('task_dependencies', sa.Column('prior_task_id', sa.Integer(), nullable=False))
    op.drop_constraint('task_dependencies_dependent_task_id_fkey', 'task_dependencies', type_='foreignkey')
    op.drop_constraint('task_dependencies_dependee_task_id_fkey', 'task_dependencies', type_='foreignkey')
    op.create_foreign_key(None, 'task_dependencies', 'blockchain_task', ['prior_task_id'], ['id'])
    op.create_foreign_key(None, 'task_dependencies', 'blockchain_task', ['posterior_task_id'], ['id'])
    op.drop_column('task_dependencies', 'dependent_task_id')
    op.drop_column('task_dependencies', 'dependee_task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_dependencies', sa.Column('dependee_task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('task_dependencies', sa.Column('dependent_task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task_dependencies', type_='foreignkey')
    op.drop_constraint(None, 'task_dependencies', type_='foreignkey')
    op.create_foreign_key('task_dependencies_dependee_task_id_fkey', 'task_dependencies', 'blockchain_task', ['dependee_task_id'], ['id'])
    op.create_foreign_key('task_dependencies_dependent_task_id_fkey', 'task_dependencies', 'blockchain_task', ['dependent_task_id'], ['id'])
    op.drop_column('task_dependencies', 'prior_task_id')
    op.drop_column('task_dependencies', 'posterior_task_id')
    # ### end Alembic commands ###
