"""empty message

Revision ID: bcabc2834c03
Revises: 0b4247c52ad5
Create Date: 2020-01-03 13:34:22.037101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcabc2834c03'
down_revision = '0b4247c52ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_task', sa.Column('uuid', sa.String(), nullable=True))
    op.create_index(op.f('ix_blockchain_task_uuid'), 'blockchain_task', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blockchain_task_uuid'), table_name='blockchain_task')
    op.drop_column('blockchain_task', 'uuid')
    # ### end Alembic commands ###
