"""empty message

Revision ID: c13b0a18676d
Revises: 02af049dc9fe
Create Date: 2019-10-26 15:19:33.822068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13b0a18676d'
down_revision = '02af049dc9fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('ignore', sa.Boolean(), nullable=True))
    op.drop_column('blockchain_transaction', 'contract_address')
    op.drop_column('blockchain_transaction', 'coinbase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('coinbase', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blockchain_transaction', sa.Column('contract_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('blockchain_transaction', 'ignore')
    # ### end Alembic commands ###
