"""Add status to synchronization_filter

Revision ID: c14405edda7c
Revises: aed2d49731a5
Create Date: 2021-07-27 15:50:42.493599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14405edda7c'
down_revision = 'aed2d49731a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synchronization_filter', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('synchronization_filter', 'status')
    # ### end Alembic commands ###
