"""empty message

Revision ID: cb57b408b032
Revises: cf6073ce51e0
Create Date: 2019-09-07 11:30:01.131319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb57b408b032'
down_revision = 'cf6073ce51e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
