"""empty message

Revision ID: cf6073ce51e0
Revises: 50df11816a5d
Create Date: 2019-09-06 19:53:49.160027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6073ce51e0'
down_revision = '50df11816a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_transaction', sa.Column('nonce_consumed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blockchain_transaction', 'nonce_consumed')
    # ### end Alembic commands ###
