"""Make synchronization_filter.contract_address unique

Revision ID: da3186c8a0f4
Revises: a51f8a70fbc8
Create Date: 2020-06-12 16:42:45.470515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3186c8a0f4'
down_revision = 'a51f8a70fbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'synchronization_filter', ['contract_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'synchronization_filter', type_='unique')
    # ### end Alembic commands ###
