"""empty message

Revision ID: e932b738ea4a
Revises: 493f16271f80
Create Date: 2019-11-17 20:06:28.281991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e932b738ea4a'
down_revision = '493f16271f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_task', sa.Column('_amount', sa.Numeric(precision=27), nullable=True))
    op.drop_column('blockchain_task', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blockchain_task', sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('blockchain_task', '_amount')
    # ### end Alembic commands ###
