"""empty message

Revision ID: f931e179d451
Revises: e39034267077
Create Date: 2020-06-11 12:15:19.531608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f931e179d451'
down_revision = 'e39034267077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synchronized_block', sa.Column('synchronization_filter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'synchronized_block', 'synchronization_filter', ['synchronization_filter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'synchronized_block', type_='foreignkey')
    op.drop_column('synchronized_block', 'synchronization_filter_id')
    # ### end Alembic commands ###
