FROM python:3.7.8-slim-stretch

# update apk repo
RUN echo "http://dl-4.alpinelinux.org/alpine/v3.7/main" >> /etc/apk/repositories && \
    echo "http://dl-4.alpinelinux.org/alpine/v3.7/community" >> /etc/apk/repositories

# install chromedriver
RUN apk update
RUN apk add chromium chromium-chromedriver

RUN apk add linux-headers gmp-dev

RUN apk add gcc g++ libffi libffi-dev libstdc++ python3-dev musl-dev

RUN apk add openssl-dev

COPY ./requirements.txt /
RUN pip install -r requirements.txt

ADD ./ /
ADD ./_docker_app_script.sh /

WORKDIR /

RUN chmod +x /_docker_app_script.sh

CMD ["/_docker_app_script.sh"]

