apiVersion: apps/v1
kind: Deployment
metadata:
  name: eth-worker
  labels:
    app: eth-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eth-worker
  template:
    metadata:
      labels:
        app: eth-worker
    spec:
      containers:
        - name: eth-worker-app
          image: gcr.io/vocal-tracer-302110/eth_worker:a9803
          imagePullPolicy: Always
          env:
            # [START cloudsql_secrets]
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql
                  key: password
            # [END cloudsql_secrets]
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3auth
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3auth
                  key: AWS_SECRET_ACCESS_KEY
            - name: LOAD_FROM_S3
              value: "true"
            - name: DEPLOYMENT_NAME
              value: "devgke"
          ports:
            - containerPort: 8080

        - image: gcr.io/cloudsql-docker/gce-proxy:1.16
          name: cloudsql-proxy
          command:
            [
              "/cloud_sql_proxy",
              "--dir=/cloudsql",
              "-instances=vocal-tracer-302110:australia-southeast1:sempo-test=tcp:5432",
              "-credential_file=/secrets/cloudsql/credentials.json",
            ]
          volumeMounts:
            - name: cloudsql-oauth-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
          # [END proxy_container]
      # [START volumes]
      volumes:
        - name: cloudsql-oauth-credentials
          secret:
            secretName: cloudsql-oauth-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir: {}
      # [END volumes]
