export const DEEP_UPDATE_USER_LIST = "DEEP_UPDATE_USER_LIST";
export const UPDATE_USER_LIST = "UPDATE_USER_LIST";

export enum LoadUserActionTypes {
  LOAD_USER_REQUEST = "LOAD_USER_REQUEST",
  LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS",
  LOAD_USER_FAILURE = "LOAD_USER_FAILURE"
}

export interface LoadUserRequestPayload {
  query: {};
  path: number;
}

export enum EditUserActionTypes {
  EDIT_USER_REQUEST = "EDIT_USER_REQUEST",
  EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS",
  EDIT_USER_FAILURE = "EDIT_USER_FAILURE"
}

export enum CreateUserActionTypes {
  CREATE_USER_REQUEST = "CREATE_USER_REQUEST",
  CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS",
  CREATE_USER_FAILURE = "CREATE_USER_FAILURE",
  RESET_CREATE_USER = "RESET_CREATE_USER"
}

export enum DeleteUserActionTypes {
  DELETE_USER_REQUEST = "DELETE_USER_REQUEST",
  DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE = "DELETE_USER_FAILURE"
}

export enum ResetPinActionTypes {
  RESET_PIN_REQUEST = "RESET_PIN_REQUEST",
  RESET_PIN_SUCCESS = "RESET_PIN_SUCCESS",
  RESET_PIN_FAILURE = "RESET_PIN_FAILURE"
}
