USER = 'user'
CUSTOM_ATTRIBUTE = 'custom_attribute_user_storage'
TRANSFER_ACCOUNT = 'transfer_account'
CREDIT_TRANSFER = 'credit_transfer'
DATE = 'date'
ALL_FILTER_TYPES = [USER, CUSTOM_ATTRIBUTE, TRANSFER_ACCOUNT, CREDIT_TRANSFER, DATE]



TRANSFER = 'transfer'
PARTICIPANT = 'participant'
ALL='all'
METRIC_TYPES = [TRANSFER, PARTICIPANT, ALL]
